### ISSUE TITLE
App is in background and background loading is disabled. Ignoring request

### ISSUE THREAD

**Issue by waleednour** [googleads/googleads-mobile-ios-examples#108]
i receive this error from admob sdk:
App is in background and background loading is disabled. Ignoring request

i call ads when app become active

**Comment by stowy** [comment]
For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
