### ISSUE TITLE
Does kGADAdSizeSmartBannerPortrait actually work?

### ISSUE THREAD

**Issue by jonnyijapan** [googleads/googleads-mobile-ios-examples#11]
Even using only a constraint of 50 points for height, a banner view setup with kGADAdSizeSmartBannerPortrait does always only pull down the "320x50 test banner" creative. Does this mean that the smart size thing does actually not work, OR, it works but there is just no matching test creative so it sends the "next nearest match" which could be 320x50 in this case - kind of thinking? I am expecting, in portrait, a 414 point wide banner on iPhone 6 Plus, 375 points on iPhone 6, 320 on other iPhones and iPods.

FYI: I came here looking for smart sized banners as advertised on your pages. The example projects showed nothing of that, I had to setup define the kGADAdSizeSmartBannerPortrait myself. A suggestion would be to show off all possible banner sizes in your sample projects. Granted they work.

There were a few other issues stemming from too old codebases. Bitcode needed to be turned off, some battling with cocoapods, adding launch images (for the ObjC project) in order to get native resolution on iPhone 6 Plus and iPhone 6, and possibly a few more issues before it was even possible to build and run properly. You might want to fix that stuff.

**Comment by ericleich** [comment]
It is valid for smart banners banners to fill an image and pad it on the sides that is the best creative to serve. Text ads also compete, and they can fit any sized request. The way the test ads are set up, there are images that are preferred and a text ad as a backfill for custom sizes that don't fit the images. So for portrait it's likely that you always get the image with padding (where appropriate) during testing.

Most of the example projects in this repo are made to be as simple as possible (to cater to our largely beginner audience), essentially the result of our [quick start](https://developers.google.com/admob/ios/quick-start) guides for banners or interstitials. For more advanced pubs like yourself, we have the APIDemo app which shows off the bulk of the rest of our APIs, and has a [demo](https://github.com/googleads/googleads-mobile-ios-examples/blob/master/Objective-C/advanced/APIDemo/APIDemo/AdMobBannerSizesViewController.m) of the various banner sizes.

The samples are meant to compile out of the box. Bitcode has been turned off in the samples as of 3 days ago. I don't see any complaints about the launch images anymore. For CocoaPods, we include the Podfile so it should be a simple "pod install" from the right directory and the run button should just work. I realize the irony that there's a compilation error in the APIDemo right now with using UIUserInterfaceIdiomTV when compiling for iOS 6... we'll get that cleaned up shortly.

**Comment by jonnyijapan** [comment]
I found the API demo later too, but didn't get full-width banned there either as far as I remember. So what you mean is, in a live app we might see full size text ads, but probably not full size image ads?
I'm not sure I can say something is exactly broken then, but if live ads don't fill the full width at all times, then I guess it would be fair not to show full width ads in the sample project either.

The whole discussion is kind of long but we, as a maker of many free-to play games have seen some bad results with banners that don't fill full width of a screen. So we are looking for ways to have banners fill that extra width. If the "smart" banners just add extra empty pixels on he sides, then that's no real change for us and we just have to go looking for another solution.

**Comment by ericleich** [comment]
The key thing here is the image inventory doesn't change. That is, I highly doubt AdWords buyers are uploading 414x50 image creatives to fit nicely within that smart banner size. They are still 320x50 and the other standard formats. So a 320x50 with padding on the sides to fill the creative is currently considered "working as intended" for these image formats. As mentioned before, text ads are molded to fit nicely into whatever size the smart banner is.

I have less visibility into what the plans are to make better use of that space for image inventory. AdMob does have a formats team that runs experiments all the time for new formats, and making smart banners is on our radar. Giving AdMob that space allows us to potentially make it better in the future without requiring an app update.

Ultimately you have to make the right call for your app. For an iPhone 6s Plus in portrait, you're likely not able to use the other 94x50 pixels on the sides of the ad anyways. In landscape, maybe you do choose to put a smaller ad in the corner of your app.
