### ISSUE TITLE
Google mobile ads sdk send endless request to their server

### ISSUE THREAD

**Issue by wixvii** [googleads/googleads-mobile-ios-examples#110]
On our iOS app we are using "google mobile ads sdk" and its send too much request to their server.

s this a problem with sdk or is it a problem in my implementation how can I check this problem. Did you face any problem like this?

Here is the request list. It never stop sending request everysecond.

here is the url of tthe request. `"https://pubads.g.doubleclick.net/gampad/ads?..."`

**Comment by stowy** [comment]
Hi @wixvii , thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
