### ISSUE TITLE
AdMob prevents promo code usage!

### ISSUE THREAD

**Issue by nbawe** [googleads/googleads-mobile-ios-examples#112]
When I use following code in the AppDelegate:

`GADMobileAds.sharedInstance().start(completionHandler: nil)`

Somehow it makes redeeming IAP promo codes broken - not finishing transactions.

Also tested previous versions of AdMob SDKs which did not use previously mentioned code in the AppDelegate and everything worked fine.

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

Thanks

Sam
