### ISSUE TITLE
Cpu Issue

### ISSUE THREAD

**Issue by Faisal-AlNeela** [googleads/googleads-mobile-ios-examples#113]
Im using this SDK for a long time. but now I have got an Issue, when an Ad is received Cpu is rise to 6% or more and stay in this value but when presenting an ad or it rise to 60% and stay in this level also when the app go to background then foreground its rise to 60%!!

I'm using an Interstitial and reworded ads.

any idea how to solve it?

<img width="1141" alt="Screen Shot 2019-07-28 at 9 42 19 PM" src="https://user-images.githubusercontent.com/8142918/62011609-1e60c000-b183-11e9-9d80-f2133384482f.png">

And you can see WebThread 

<img width="854" alt="Screen Shot 2019-07-28 at 9 42 46 PM" src="https://user-images.githubusercontent.com/8142918/62011615-31739000-b183-11e9-8c2e-988c5d0d119d.png">

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
