### ISSUE TITLE
Swift + Cocoapods + use_frameworks!

### ISSUE THREAD

**Issue by austimkelly** [googleads/googleads-mobile-ios-examples#12]
Has anyone found a clever way to install the Google Ads SDK in a swift app that uses `use_frameworks!` in the Podfile?

Bumping up against this issue: https://github.com/CocoaPods/CocoaPods/issues/3267

Where my error is:

```
[!] The 'Pods-PROJECTNAME' target has transitive dependencies that include static binaries: (/Users/tim.kelly/code//Example/PROJECTNAME/Pods/Google-Mobile-Ads-SDK/GoogleMobileAdsSdkiOS-7.6.0/GoogleMobileAds.framework)
```

**Comment by austimkelly** [comment]
Here's an example project: https://github.com/austimkelly/cocoapodsbug

Any tip on how to workaround this would be helpful!

**Comment by ianterrell** [comment]
I've worked around this for the time being by...

1. Link the subspec to the framework: https://github.com/ianterrell/cocoapodsbug/commit/0e7577350d73bf9f4e601f1809c640644c5c825e#diff-ab0ed0509b1853d5d9d0d293a97315adR24
1. Include the dependency as a pod at the top level: https://github.com/ianterrell/cocoapodsbug/commit/0e7577350d73bf9f4e601f1809c640644c5c825e#diff-7bbb32dd417d3161906681980e573654R6
1. Monkey patch the xcconfig file generation to omit the framework from the top level Pods project: https://github.com/ianterrell/cocoapodsbug/commit/0e7577350d73bf9f4e601f1809c640644c5c825e#diff-7bbb32dd417d3161906681980e573654R9

I don't like it — but it seems to work so far. :)

**Comment by JJLewis** [comment]
Hi @ianterrell I had a look through your workaround and could figure out how to do it.
If you don't mind, could you do your work around on this please. (https://github.com/JJLewis/JLGlobalAdBanner)
I am still quite shallow in the world of CocoaPods, so have no experience in subspecs, etc.
Thanks a lot.

**Comment by austimkelly** [comment]
Thank you @ianterrell for the forked demo. The workaround seems to work OK if we have a customer that might get stuck in this position. Hopefully the ads framework will ship with dynamic lib in the future!
