### ISSUE TITLE
Example App Logic Bug

### ISSUE THREAD

**Issue by VeritasDev** [googleads/googleads-mobile-ios-examples#121]
In the RewardedVideoExample project, inside `ViewController.swift` line 87 is the following code:

```
fileprivate func startNewGame() {
    gameState = .playing
    counter = gameLength
    playAgainButton.isHidden = true
    if !adRequestInProgress && rewardedAd?.isReady == false {
      rewardedAd = GADRewardedAd(adUnitID: "ca-app-pub-3940256099942544/1712485313")
      adRequestInProgress = true
      rewardedAd?.load(GADRequest()) { error in
        self.adRequestInProgress = false
        if let error = error {
          print("Loading failed: \(error)")
        } else {
          print("Loading Succeeded")
        }
      }
    }
```
This causes the sample app to never load, because of the way optionals work in swift.

`rewardedAd?.isReady == false` always evaluates as false in the sample app because the rewarded ad is `nil`, and calling `isReady` on `nil` returns `nil`, and in swift `nil != false`.

Changing that line to this code works:

`if !adRequestInProgress && !(rewardedAd?.isReady ?? false) {`

**Comment by JillSong** [comment]
Thank you for reporting! Fixed:)
