### ISSUE TITLE
iPhone Landscape can not be closed

### ISSUE THREAD

**Issue by break2k** [googleads/googleads-mobile-ios-examples#123]
We are using the `GoogleMobileAds` quite a while. Since the update to `7.50.0` we are facing an ad we can not close in landscape due to not being able to scroll in that view? Any tricks we can leverage here?

See attached screenshot:

![IMG_0016](https://user-images.githubusercontent.com/506722/66385532-ef579d80-e9c0-11e9-8d6d-75a4ef1676ec.PNG)

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on
our support forum at
https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios -
they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps
only, as more in depth support for your specific issues is handled by our
support team on the forum.

When posting to the forum, please also provide specific details including
any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details
including which sample app and specific steps to reproduce the issue.

**Comment by break2k** [comment]
Thank you for the feedback. We were able to narrow down the issue to an AdServer configuration for specific ads. Take care!
