### ISSUE TITLE
Request Error: No ad to show.

### ISSUE THREAD

**Issue by tanhuang** [googleads/googleads-mobile-ios-examples#131]
I tried to use the sample adUnit ID in my app, which works great to show video ads from your server. The sample ID I am using: ca-app-pub-3940256099942544544 / 2934735716.

However, before I release it, I do need to try my own adUnitID, yes, I just need to check it out instead of clicking it. Therefore, I replaced the adUnitID with my own.

I added GADApplicationIdentifier in info.plist: ca-app-pub-1006434852352207~3091593278

AppDelegate

GADMobileAds *ads = [GADMobileAds sharedInstance];
    [ads startWithCompletionHandler:^(GADInitializationStatus * _Nonnull status) {
        NSLog(@"%@", status);
    }];

HomeViewController

        self.adBannerView = [[GADBannerView alloc] initWithAdSize:kGADAdSizeBanner];
        self.adBannerView.delegate = self;
        [self addBannerViewToView:self.adBannerView];
        self.adBannerView.adUnitID = @"ca-app-pub-1006434852352207/1858703979";
        self.adBannerView.rootViewController = self;
        [self.adBannerView loadRequest:[GADRequest request]];

Logging

Error Domain=com.google.admob Code=1 "Request Error: No ad to show."

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on
our support forum at
https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios -
they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps
only, as more in depth support for your specific issues is handled by our
support team on the forum.

When posting to the forum, please also provide specific details including
any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details
including which sample app and specific steps to reproduce the issue.
