### ISSUE TITLE
customRenderedBannerViewDelegate sample

### ISSUE THREAD

**Issue by hiko-prod** [googleads/googleads-mobile-ios-examples#146]
Is it possible to add an example, on how to use DFPCustomRenderedAd

https://developers.google.com/ad-manager/mobile-ads-sdk/ios/api/reference/Classes/DFPCustomRenderedAd

**Comment by jaylester7** [comment]
[US-Privacy-USER-SIGNAL-API-SPEC-v1.0.pdf](https://github.com/googleads/googleads-mobile-ios-examples/files/4219774/US-Privacy-USER-SIGNAL-API-SPEC-v1.0.pdf)

**Comment by stowy** [comment]
Hi @hiko-prod - this format is no longer supported. We recommend using `GADNativeCustomTemplateAd` format [as seen here](https://github.com/googleads/googleads-mobile-ios-examples/blob/master/Objective-C/admanager/AdManagerCustomRenderingExample/AdManagerCustomRenderingExample/ViewController.m#L180).
