### ISSUE TITLE
swift Admob banner ad  Memory lack 

### ISSUE THREAD

**Issue by crossle** [googleads/googleads-mobile-ios-examples#16]
1. So high memory when admob banner ad load
<img width="1074" alt="screen shot 2016-04-27 at 19 09 45" src="https://cloud.githubusercontent.com/assets/1675131/14850446/b2aaedec-0cab-11e6-8dc0-8d7c50ffa186.png">

2. The memory  has been increasing, also used facebook ad, very low memory, and auto resize banner

**Comment by temrich** [comment]
Do you see this high memory usage with our iOS Banner Example app? If not, please visit our [support forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) to browse any SDK related issues.

**Comment by benchris921** [comment]
I could see in the Swift iOS Banner Example app as well.  Memory increasing whenever new request received.

**Comment by ericleich** [comment]
When investigating issues like this, the things we look for are:

1) Leaks tool to see if anything is actually leaked
2) Memory usage increasing linearly with each ad request (think 10-20 reloads, not just 2)

When refreshing an ad for the first time, another WebView is used in the background to load and render while the first ad is still showing, so currently used memory goes up. But if you keep refreshing, memory should stay constant since older webviews get recycled.

**Comment by benchris921** [comment]
Hi ericleich,  Thank you for response. From my testing,  it is true that memory stays while keep refreshing,    But at first 4 ~ 5 refreshings, it increased memory usage. 

And also, is there any retained instance as a background? I mean :  memory usage is not decreased once it has been raised even after setting the delegate and rootViewController to nil,  and remove ad view from super view and set it to nil.   Tried to dismiss view controller that contains admob view,  but memory not decreased,  somewhere any instance occupies memory usage, I think.

So,  now I have created singleton class and controls the admob instance (for BannerAdView and adRequest).

Please share any information if you can for this memory keep.

Thanks,
Ben

**Comment by ericleich** [comment]
Hey Ben,

I think it's a side effect of using WebView. When I create a new WebView:

    self.webView = [[UIWebView alloc] initWithFrame:CGRectMake(0, 0, 100, 100)];
    [self.webView loadRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"https://www.google.com"]]];
    [self.view addSubview:self.webView];

And then later remove all references:

    [self.webView removeFromSuperview];
    self.webView = nil;

I'm still seeing similar memory usage compared to doing the same for a banner ad.
