### ISSUE TITLE
IDFA prompt on iOS14

### ISSUE THREAD

**Issue by dbaroncelli** [googleads/googleads-mobile-ios-examples#162]
Will AdMob still be based on IDFA on iOS14?
Are we going to expect that all apps using AdMob on iOS14 will prompt the "Allow Tracking" dialog to users?
https://www.forbes.com/sites/johnkoetsier/2020/06/24/apple-just-made-idfa-opt-in-sending-an-80-billion-industry-into-upheaval/#22c20dc6712c

**Comment by stowy** [comment]
Hi, thanks for your query.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

For general support, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios - they will be able to help answer your concern efficiently.
