### ISSUE TITLE
After upgrading Google-Mobile-Ads-SDK from 7.57.0 to 7.62.0, rewarded ads and banner ads cannot be requested.

### ISSUE THREAD

**Issue by mafaming** [googleads/googleads-mobile-ios-examples#164]
After upgrading Google-Mobile-Ads-SDK from 7.57.0 to 7.62.0, rewarded ads and banner ads cannot be requested.
Request for rewarded advertising error: Error Domain=com.google.admob Code=11 "Request Error: Internal error." UserInfo={NSLocalizedDescription=Request Error: Internal error., gad_response_info= ** Response Info **
     Response ID: (null)
     Network: (null)

   ** Mediation line items **
}

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
