### ISSUE TITLE
Framework missing

### ISSUE THREAD

**Issue by TamilRaja** [googleads/googleads-mobile-ios-examples#17]
Module GoogleMobileAds not found...

**Comment by ericleich** [comment]
The sample doesn't come with the SDK. You either have to download the SDK manually and include it, or use CocoaPods. To [get started](https://cocoapods.org/) CocoaPods, run `gem install cocoapods`, and then run `pod install` from your project's main directory where the `Podfile` is.

**Comment by MattMur** [comment]
@ericleich After running "pod update" I'm getting this error `[!] The dependency 'Google-Mobile-Ads-SDK (~> 7.5)' is not used in any concrete target.`
And no .xcworkspace file is built

**Comment by austimkelly** [comment]
I think for Cocoapoda 1.0 you need to specify the target, like so:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target "DFPNativeExample" do
	pod 'Google-Mobile-Ads-SDK', '~> 7.5'
end
```

**Comment by temrich** [comment]
Hi Matt, are you still having issues with running pod update with our example apps?
