### ISSUE TITLE
App events not working when banner ad is requested using GADAdLoader

### ISSUE THREAD

**Issue by jadhavp** [googleads/googleads-mobile-ios-examples#172]
## Issue
GADAppEventDelegate method adView:didReceiveAppEvent:withInfo: not called when ad is requested using GADAdLoader. 

Please refer to [Sample application](https://github.com/jadhavp/ios-sample-apps/tree/master/AdManagerBannerExample) for reproducing the issue.

`Note: adView:didReceiveAppEvent:withInfo works properly with DFPBannerView, also Android counterpart work as expected` 

## Setup / Env
**Xcode** - Version 11.3.1 (11C504)
**Google Ads SDK** - Google-Mobile-Ads-SDK (7.65.0)

**Adunit** - /6499/example/APIDemo/AppEvents 
**Ad Type** - kGADAdLoaderAdTypeDFPBanner
App uses GADAdloader for loadin banner ad, it uses valid [DFPBannerViewOptions](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/native-banner#dfpbannerviewoptions) with valid `appEventDelegate` set, as expected.

Sample app - [HERE](https://github.com/jadhavp/ios-sample-apps/tree/master/AdManagerBannerExample)

## Expectation
As per [THIS](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/native-banner#dfpbannerviewoptions) guide app event should work with GADAdloader.

Thanks!

**Comment by toptomsk** [comment]
> ## Issue
> GADAppEventDelegate method adView:didReceiveAppEvent:withInfo: not called when ad is requested using GADAdLoader.
> 
> Please refer to [Sample application](https://github.com/jadhavp/ios-sample-apps/tree/master/AdManagerBannerExample) for reproducing the issue.
> 
> `Note: adView:didReceiveAppEvent:withInfo works properly with DFPBannerView, also Android counterpart work as expected`
> 
> ## Setup / Env
> **Xcode** - Version 11.3.1 (11C504)
> **Google Ads SDK** - Google-Mobile-Ads-SDK (7.65.0)
> 
> **Adunit** - /6499/example/APIDemo/AppEvents
> **Ad Type** - kGADAdLoaderAdTypeDFPBanner
> App uses GADAdloader for loadin banner ad, it uses valid [DFPBannerViewOptions](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/native-banner#dfpbannerviewoptions) with valid `appEventDelegate` set, as expected.
> 
> Sample app - [HERE](https://github.com/jadhavp/ios-sample-apps/tree/master/AdManagerBannerExample)
> 
> ## Expectation
> As per [THIS](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/native-banner#dfpbannerviewoptions) guide app event should work with GADAdloader.
> 
> Thanks!

You can try to set Delegate after received banner like this, it works for me:
`func adLoader(_ adLoader: GADAdLoader, didReceive bannerView: DFPBannerView) {
        bannerView.center = CGPoint(x: SCREEN_WIDTH/2, y: SCREEN_HEIGHT/2)
        bannerView.appEventDelegate = self
        self.view.addSubview(bannerView)
  }`

**Comment by jadhavp** [comment]
> > ## Issue
> > GADAppEventDelegate method adView:didReceiveAppEvent:withInfo: not called when ad is requested using GADAdLoader.
> > Please refer to [Sample application](https://github.com/jadhavp/ios-sample-apps/tree/master/AdManagerBannerExample) for reproducing the issue.
> > `Note: adView:didReceiveAppEvent:withInfo works properly with DFPBannerView, also Android counterpart work as expected`
> > ## Setup / Env
> > **Xcode** - Version 11.3.1 (11C504)
> > **Google Ads SDK** - Google-Mobile-Ads-SDK (7.65.0)
> > **Adunit** - /6499/example/APIDemo/AppEvents
> > **Ad Type** - kGADAdLoaderAdTypeDFPBanner
> > App uses GADAdloader for loadin banner ad, it uses valid [DFPBannerViewOptions](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/native-banner#dfpbannerviewoptions) with valid `appEventDelegate` set, as expected.
> > Sample app - [HERE](https://github.com/jadhavp/ios-sample-apps/tree/master/AdManagerBannerExample)
> > ## Expectation
> > As per [THIS](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/native-banner#dfpbannerviewoptions) guide app event should work with GADAdloader.
> > Thanks!
> 
> You can try to set App Event Delegate after received banner like this, it works for me:
> 
> > func adLoader(_ adLoader: GADAdLoader, didReceive bannerView: DFPBannerView) {
> > bannerView.center = CGPoint(x: SCREEN_WIDTH/2, y: SCREEN_HEIGHT/2)
> > bannerView.appEventDelegate = self
> > self.view.addSubview(bannerView)
> > }

Thanks, it works.

**Comment by pboisso** [comment]
Following...

**Comment by malandr2** [comment]
Closing this issue as we no longer support DFPBanners. Follow the [docs](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/banner#app_events) to properly configure [appEventsDelegate](https://developers.google.com/admob/ios/api/reference/Classes/GAMBannerView#appeventdelegate).
