### ISSUE TITLE
No interstitial ad to show (Ad unit id example taken from documentation)

### ISSUE THREAD

**Issue by tomaszwojcik** [googleads/googleads-mobile-ios-examples#18]
I have a hard time integrating AdMob with existing project - receiving `No ad to show.` all the time.
However, when I create a new project I have no problems with retrieving ads with the same code.

My main project includes Google Analytics pod, I commented out it's setup with no success.
On both existing and new project ATS is disabled.

I've tried setting `IS_ADS_ENABLED` to `YES` for analytics but then it shows an error that I have to include `Google/Ads` in the pods file which results with `target has frameworks with conflicting names: GoogleMobileAds.`
When I comment out `Google-Mobile-Ads-SDK` and leave `Google/Ads` I get build errors.

Both projects are with target iOS >= 8.0 + Swift.
```
class AdViewController: UIViewController {
    private var interstitial: GADInterstitial!

    override func viewDidLoad() {
        super.viewDidLoad()
        interstitial = GADInterstitial(adUnitID: "ca-app-pub-3940256099942544/4411468910")

        let request = GADRequest()
        // Requests test ads on test devices.
        request.testDevices = ["eade18b6188d6fe8214f399759097686"]

        interstitial.delegate = self
        interstitial.loadRequest(request)
    }
}

extension AdViewController: GADInterstitialDelegate {
    /// Called when an interstitial ad request succeeded.
    func interstitialDidReceiveAd(ad: GADInterstitial!) {
        print("interstitialDidReceiveAd")
    }

    /// Called when an interstitial ad request failed.
    func interstitial(ad: GADInterstitial!, didFailToReceiveAdWithError error: GADRequestError!) {
        print("interstitial:didFailToReceiveAdWithError: \(error.localizedDescription)")
    }

    /// Called just before presenting an interstitial.
    func interstitialWillPresentScreen(ad: GADInterstitial!) {
        print("interstitialWillPresentScreen")
    }

    /// Called before the interstitial is to be animated off the screen.
    func interstitialWillDismissScreen(ad: GADInterstitial!) {
        print("interstitialWillDismissScreen")
    }

    /// Called just after dismissing an interstitial and it has animated off the screen.
    func interstitialDidDismissScreen(ad: GADInterstitial!) {
        print("interstitialDidDismissScreen")
    }

    /// Called just before the application will background or terminate because the user clicked on an
    /// ad that will launch another app (such as the App Store).
    func interstitialWillLeaveApplication(ad: GADInterstitial!) {
        print("interstitialWillLeaveApplication")
    }
}
```

**Comment by ericleich** [comment]
I'm not sure why you're getting `No ad to show` in your project's environment. Sometimes something happens to the test ad configuration and it doesn't work, but I just tried it and it seems to be working fine, and you've gotten it in your test environment.

To further debug the multiple instances of GoogleMobileAds, can you clarify what your Podfile looks like so I can see exactly what pods you're referencing? I ask because I don't see a `Google/Ads` pod, just a [Google/AdMob](https://github.com/CocoaPods/Specs/blob/master/Specs/Google/2.0.4/Google.podspec.json#L96). `Google/AdMob` depends on `GoogleMobileAds`, which is the same library as `Google-Mobile-Ads-SDK`. So you'll get duplicate copies of GoogleMobileAds if both of these libraries are referenced. We're looking to clean that up so there aren't 2 pods for the same library.

**Comment by tomaszwojcik** [comment]
You're right it's `Google/AdMob`, not `Google/Ads`.

The problem is that I've been trying that code for few days now, with no success on my main project. :/

Podfile (CocoaPods 0.39.0, can migrate to 1.0.0):
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

def project_pods
  pod 'Alamofire', '~> 3.0'
  pod 'SWRevealViewController', '~> 2.3'
  pod 'StreamingKit', git: 'git@github.com:tomaszwojcik/StreamingKit.git'

  pod 'SDWebImage', '~> 3.7'

  pod 'FBSDKCoreKit', '~> 4.10'
  pod 'FBSDKShareKit', '~> 4.10'
  pod 'FBSDKLoginKit', '~> 4.10'

  pod 'Google/Analytics'
  pod 'Google-Mobile-Ads-SDK', '~> 7.0'
end

def test_pods
  pod 'Quick', '~> 0.9.0'
  pod 'Nimble', '3.0.0'
end

target 'Project' do
  project_pods
end

target 'ProjectTests' do
  project_pods
  test_pods
end
```

**Comment by tomaszwojcik** [comment]
Looks like I found the issue.

In AppDelegate I change the user-agent, and it seems the AdMob doesn't like that at all.
```
NSUserDefaults.standardUserDefaults().registerDefaults(["UserAgent" : "MyUserAgent"])
```

Now I'm able to retrieve test ads all the time.
@ericleich  Can you please add that to AdMob documentation?

**Comment by ericleich** [comment]
Good catch, ads won't load if the user agent is changed. I'll think about where it makes sense to add it to the docs. We may have to create a new troubleshooting page to hold content like this.

**Comment by nihp** [comment]
@ericleich I am getting the below error after upgrading the Google Ads sdk to the latest version 

'GoogleMobileAds/GADInterstitialDelegate.h' file not found

**Comment by ericleich** [comment]
@nihp this is expected behavior. Both of those headers no longer exist in v9.x of the iOS SDK. The examples at HEAD of this repo use the latest delegates.

**Comment by nihp** [comment]
@ericleich Could you please provide any alternative for the same one. 

I have removed the GADInAppPurchaseDelegate imports.

But the GADInterstitialDelegate needs to be used by many of the implemetnation. Could you please provide. the alternate for this.

**Comment by ericleich** [comment]
@nihp The GADFullScreenContentDelegate protocol has replaced GADInterstitialDelegate. Please see https://developers.google.com/admob/ios/migration#expandable-1 for more information. You can also check out the InterstitialExample in this repo to see how it’s implemented in v9.
