### ISSUE TITLE
Open ads not working

### ISSUE THREAD

**Issue by Vladbruno** [googleads/googleads-mobile-ios-examples#194]
Hello!
I'm trying to setup open ads on swift project.

I use this code:

  import GoogleMobileAds

  class AppDelegate: UIResponder, UIApplicationDelegate, GADFullScreenContentDelegate {

    var appOpenAd: GADAppOpenAd?
    var loadTime = Date()

  func requestAppOpenAd() {
    let request = GADRequest()
    GADAppOpenAd.load(withAdUnitID: "ca-app-pub-3940256099942544/5662855259",
                      request: request,
                      orientation: UIInterfaceOrientation.portrait,
                      completionHandler: { (appOpenAdIn, _) in
                        self.appOpenAd = appOpenAdIn
                        self.appOpenAd?.fullScreenContentDelegate = self
                        self.loadTime = Date()
                        print("Ad is ready")
                      })
}

  func tryToPresentAd() {
    if let gOpenAd = self.appOpenAd, let rwc = self.window?.rootViewController,     wasLoadTimeLessThanNHoursAgo(thresholdN: 4) {
        gOpenAd.present(fromRootViewController: rwc)
    } else {
        self.requestAppOpenAd()
    }
}

  func wasLoadTimeLessThanNHoursAgo(thresholdN: Int) -> Bool {
    let now = Date()
    let timeIntervalBetweenNowAndLoadTime = now.timeIntervalSince(self.loadTime)
    let secondsPerHour = 3600.0
    let intervalInHours = timeIntervalBetweenNowAndLoadTime / secondsPerHour
    return intervalInHours < Double(thresholdN)
}

  func applicationDidBecomeActive(_ application: UIApplication) {
    print("applicationDidBecomeActive")
    self.tryToPresentAd()
}

But the problem is applicationDidBecomeActive function is not calling. Is there another way to call tryToPresentAd()?

**Comment by namdhis** [comment]
Did you find the way to fix this issue? @Vladbruno

**Comment by Vladbruno** [comment]
> Did you find the way to fix this issue? @Vladbruno

Hey, try this
https://stackoverflow.com/a/67574413/11963484
