### ISSUE TITLE
Undefined symbols for architecture x86_64 - Xcode 12.4

### ISSUE THREAD

**Issue by Vukovi** [googleads/googleads-mobile-ios-examples#199]
I am using CocoaPods to insert GoogleAds in the app i am working on. The app is modularised, successfully using Firebase and MaterialDesign inside of it. GoogleAds are very important to the client so it is a must for the project. First of all, i added dependency 'Google-Mobile-Ads-SDK' and i have warnings after pod install / pod update -

[!] Can't merge user_target_xcconfig for pod targets: ["Appboy-iOS-SDK", "ContentCards", "Core", "InAppMessage", "NewsFeed", "UI", "Google-Mobile-Ads-SDK"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

I have successful build after importing GoogleMobileAds in my designated file. But as soon as i want to instantiate GADAdLoader i end up with failing build like this:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GADAdLoader", referenced from:
      objc-class-ref in PostListViewController.o
  "_kGADAdLoaderAdTypeCustomNative", referenced from:
      Post.PostListViewController.viewDidLoad() -> () in PostListViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

How to solve this, please help.

**Comment by Vukovi** [comment]
Closing this issue

**Comment by CaptainHaider** [comment]
how did you solve this?
