### ISSUE TITLE
Examples for SwiftUI

### ISSUE THREAD

**Issue by ForceGT** [googleads/googleads-mobile-ios-examples#200]
Is it possible that we have examples for SwiftUI for each case?

**Comment by mjunkmyjunk** [comment]
The current documentation only has Objective-C

**Comment by ForceGT** [comment]
> The current documentation only has Objective-C

Yes I see that and all of Firebase still has Obj C code
I don't understand why they love it so much

**Comment by Raymondkltse** [comment]
I am new to iOS programmer (work on Android in past few years) and using  SwiftUI. I should say yes, there is very little resources for swift + swiftui + admob SDK v8.

I am having trouble to make nativeads to work correctly for almost a days or two. Google is not quite updating there code in iOS version.

**Comment by hbanzon** [comment]
Hi, I wanted to check in on this thread.  I am also moving our app to SwiftUI and am looking for documentation and/or examples on getting Google Ad Manager Ads with SwiftUI.

Please advise.

**Comment by malandr2** [comment]
Happy to share we have just released our [SwiftUI sample app](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Swift/advanced/SwiftUIDemo).
