### ISSUE TITLE
Can not support custom targeting vlaue as "string array" in Mobile Ads SDK for iOS anymore ? 

### ISSUE THREAD

**Issue by jin-jobs** [googleads/googleads-mobile-ios-examples#207]
![image](https://user-images.githubusercontent.com/17607205/110286351-1ee05e80-8028-11eb-89d7-1b28d82076f7.png)

Until now, when requesting an advertisement, a string array could be delivered to the value area by custom targeting, and it is very useful.

However, as we looked at the migration process along with the new SDK guide, we were unable to deliver the string array as a custom targeting value.

Can you tell if this is an SDK bug, or if the feature is gone, or if there is an alternative?

**Comment by vardaanmittal09** [comment]
I have the same issue. Can someone take a look?

**Comment by vardaanmittal09** [comment]
DFPRequest *request = [DFPRequest request];
request.customTargeting = @{@"gender" : @"male", @"section" : @[ @"sports", @"finance"]};

With GAMRequest the same can be accomplished with this:

GAMRequest *request = [GAMRequest request];
request.customTargeting = @{@"gender" : @"male", @"section" : @"sports,finance"};

In Swift it could be like this:

let request = GAMRequest()
request.customTargeting = ["gender" : "male", "section" : "sports,finance"]

**Comment by alfodei22** [comment]
https://alfawadei.blogspot.com/?m=1
