### ISSUE TITLE
ObjC rewardedVideoAd example Depreciated 

### ISSUE THREAD

**Issue by NickCracchiolo** [googleads/googleads-mobile-ios-examples#21]
The rewarded video ad objective-c example uses a UIAlertView to notify the user when the video add is not ready. However that was depreciated in iOS 8. UIAlertController should be used instead for iOS 8+.

**Comment by ericleich** [comment]
We make the sample apps conform to iOS 6 since the Google Mobile Ads SDK supports back to iOS 6. We could check the iOS version and use UIAlertController if on iOS 8 and up, but we'd still need to keep the UIAlertView code around in the sample. So we opted for simplicity and only used UIAlertVIew.
