### ISSUE TITLE
SPM

### ISSUE THREAD

**Issue by YurchukV** [googleads/googleads-mobile-ios-examples#212]
Hello, please add SPM support

**Comment by csjones** [comment]
Any plans to support? I know [GoogleSignIn](https://github.com/google/GoogleSignIn-iOS) just got support recently.

**Comment by ingconti** [comment]
i9n 2021 is a SHAME we don't have swift AND SPM.
cocoa Pods has been awful since 2011.

**Comment by frank-dsouza** [comment]
What's the Status in SPM support ?

**Comment by Rvaler** [comment]
Any plans on adding support for SPM?
