### ISSUE TITLE
GADFullScreenAdViewController shouldAutorotate is returning YES

### ISSUE THREAD

**Issue by omairpanwar** [googleads/googleads-mobile-ios-examples#213]
when i play video in land scape mode and show ad in landscape mode the app crashes with this error "GADFullScreenAdViewController shouldAutorotate is returning YES"

**Comment by RiverboatGambler** [comment]
Same issue and it's becoming more and more common

**Comment by p0w1nd** [comment]
I'm having the same problem. My game is made with Unity and using ironSource mediation with AdMob, but I think under the hood it's still using iOS SDK of AdMob. It seems the crash happens when the game is in portrait-only mode but the AdMob ad to be displayed is landscape.

**Comment by p0w1nd** [comment]
Found a related closed issue: https://github.com/googleads/googleads-mobile-ios-examples/issues/221

**Comment by Whyser** [comment]
We have this issue as well. I would suggest you report it here (see below) to let them know it's a real issue:
https://groups.google.com/g/google-admob-ads-sdk/c/Ej6KHUzartk

**Comment by malandr2** [comment]
Closing this issue. See https://github.com/googleads/googleads-mobile-ios-examples/issues/221 for next steps.
