### ISSUE TITLE
No ad was shown on iOS 14 simulator

### ISSUE THREAD

**Issue by damozhang** [googleads/googleads-mobile-ios-examples#214]
No ad was shown when I run these examples.
I have added some code for iOS 14 following https://developers.google.com/admob/ios/ios14, and I got the same result.

The following is some debug info.

-------------------------

> 2021-04-01 14:07:27.429537-0700 APIDemo[18617:10377222] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x60000226e9a0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
> 2021-04-01 14:07:27.470324-0700 APIDemo[18617:10377222] WF: _userSettingsForUser : (null)
> 2021-04-01 14:07:27.470463-0700 APIDemo[18617:10377222] WF: _WebFilterIsActive returning: NO
> 2021-04-01 14:07:27.642407-0700 APIDemo[18617:10377222] [Process] 0x7f84b70da020 - [pageProxyID=19, webPageID=20, PID=18622] WebPageProxy::didFailProvisionalLoadForFrame: frameID = 3, domain = NSURLErrorDomain, code = -1004
> 2021-04-01 14:07:27.665129-0700 APIDemo[18617:10377222] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=3 "Target is not running or required target entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"Background" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Target is not running or required target entitlement is missing}>
> 2021-04-01 14:07:27.665249-0700 APIDemo[18617:10377222] [ProcessSuspension] 0x1145feb00 - ProcessAssertion: Failed to acquire RBS Background assertion 'WebProcess Background Assertion' for process with PID 18622, error: Error Domain=RBSAssertionErrorDomain Code=3 "Target is not running or required target entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"Background" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Target is not running or required target entitlement is missing}
> 2021-04-01 14:07:27.673039-0700 APIDemo[18617:10377222] [assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}>
> 2021-04-01 14:07:27.673143-0700 APIDemo[18617:10377222] [ProcessSuspension] 0x1145feb80 - ProcessAssertion: Failed to acquire RBS Background assertion 'WebProcess Background Assertion' for process with PID 18622, error: Error Domain=RBSAssertionErrorDomain Code=2 "Specified target process does not exist" UserInfo={NSLocalizedFailureReason=Specified target process does not exist}

**Comment by G0561** [comment]
> Target is not running or required target entitlement is missing

解决了没？ 貌似现在ios16 已经不显示广告了，官方的例子也是一样的

**Comment by NVentimiglia** [comment]
This issue does not look related to Admob. If you feel this is in error, please reopen with some more specifics.
