### ISSUE TITLE
UIWebView

### ISSUE THREAD

**Issue by ZhangD123** [googleads/googleads-mobile-ios-examples#215]
我使用grep -r "UIWebView" .命令检测，8.3.0最新版本显示仍然包含UIWebView

**Comment by Joyeye** [comment]
用英文啊，大哥，你中文的话，很多开发人员看不懂。我也遇到了，也发一下问题

**Comment by Joyeye** [comment]
新版本已经修复此问题。

**Comment by G0561** [comment]
> 我使用grep -r "UIWebView" .命令检测，8.3.0最新版本显示仍然包含UIWebView

iOS16 你们的能显示广告吗？ 更新了ios16.0.1 ，admob 广告不显示了， 现在下载官方的例子意义不显示广告，你们遇到过没

**Comment by G0561** [comment]
> 用英文啊，大哥，你中文的话，很多开发人员看不懂。我也遇到了，也发一下问题

> 我使用grep -r "UIWebView" .命令检测，8.3.0最新版本显示仍然包含UIWebView

iOS16 你们的能显示广告吗？ 更新了ios16.0.1 ，admob 广告不显示了， 现在下载官方的例子意义不显示广告，你们遇到过没

**Comment by NVentimiglia** [comment]
Closing this old issue. Please reopen with a description in english if you still need help.
