### ISSUE TITLE
Can compile swift test project

### ISSUE THREAD

**Issue by masterfego** [googleads/googleads-mobile-ios-examples#22]
GADInterstitialDelegate: use of undeclared type"GDAIntertitial Delegate"

First I do a pod install but I can build the project. 

I'm in Xcode 7.3.1

**Comment by ericleich** [comment]
Which project are you running? I was able to download, run pod install, and run the interstitial swift example on Xcode 7.3.1 just now.

**Comment by masterfego** [comment]
This example: Swift/admob/InterstitialExample/

**Comment by ericleich** [comment]
If you run pod --version do you get 1.0.0 or higher?

**Comment by joe528** [comment]
I am actually seeing the same problem after I call 'pod install' and I still cannot compile the sample project because these undeclared types...

Any further tip?

**Comment by temrich** [comment]
We recently updated our example apps. Please let us know if you are still having issues running the Swift Native Advanced example app.

**Comment by dogejinx** [comment]
unfortunately, the error about segmentation fault 11 still happened to me.

**Comment by temrich** [comment]
Can you provide the steps you are taking to get to the segmentation fault (starting with the example app that you are downloading and using)?
