### ISSUE TITLE
On version 8 update adDidDismissFullScreenContent is never called 

### ISSUE THREAD

**Issue by imrankst1221** [googleads/googleads-mobile-ios-examples#220]
I am using **GADRewardedAd** and my requirement is when ads closed then it showing a view.  `adDidPresentFullScreenContent() `is called but the `adDidDismissFullScreenContent()` method are never called. 

```
private var rewardedAdView: GADRewardedAd!
GADRewardedAd.load(withAdUnitID: UserDefaults.standard.string(forKey: Constants.ADMOB_KEY_AD_REWARDED) ?? "",
                            request: GADRequest(), completionHandler: { (ad, error) in
                              if let error = error {
                                print("Rewarded ad failed to load with error: \(error.localizedDescription)")
                                return
                              }
                              self.rewardedAdView = ad
                              self.rewardedAdView.fullScreenContentDelegate = self
                            }
```

```
private func showRewardedAds(){
        self.isAdEarnComplete = false
        if let ad = rewardedAdView {
              ad.present(fromRootViewController: self,
                       userDidEarnRewardHandler: {
                               showToast(viewContoler: self, message: "Your coupon is ready!")
                       }
              )
    }

```

```
extension HomeViewController: GADFullScreenContentDelegate{
    func adDidPresentFullScreenContent(_ ad: GADFullScreenPresentingAd) {
        print("Rewarded ads present")
    }
    
    func adDidDismissFullScreenContent(_ ad: GADFullScreenPresentingAd) {
        print("Rewarded ads dismiss")
    }
    
       
    func ad(_ ad: GADFullScreenPresentingAd, didFailToPresentFullScreenContentWithError error: Error) {
        printLog(tag: TAG, message:  "Error: \(error.localizedDescription)")
    }
}
```

**Comment by BlobTheKat** [comment]
same problem here. Any updates?

**Comment by KevinQuisquater** [comment]
`adDidPresentFullScreenContent` doesn't seem to be part of `GADFullScreenContentDelegate` anymore ([documentation](https://developers.google.com/admob/ios/api/reference/Protocols/GADFullScreenContentDelegate)), despite still being present in the sample code:

https://github.com/googleads/googleads-mobile-ios-examples/blob/40ccc2d702a372ec7175db605174a12368581125/Swift/admob/RewardedVideoExample/RewardedVideoExample/ViewController.swift#L192

Has it been replaced by/renamed into `adDidRecordImpression`?
They do not seem to mean the same thing.

**Comment by malandr2** [comment]
Hi @imrankst1221,

@KevinQuisquater is correct, per the [documentation](https://developers.google.com/admob/ios/api/reference/Protocols/GADFullScreenContentDelegate#-addidpresentfullscreencontent:), you should be using [-adWillPresentFullScreenContent:](https://developers.google.com/admob/ios/api/reference/Protocols/GADFullScreenContentDelegate#-adwillpresentfullscreencontent:) instead

**Comment by leo-beliakov** [comment]
@malandr2 Why did you close this issue? The issue is about the `adDidDismissFullScreenContent` callback not being called. It doesn't have anything to do with `adWillPresentFullScreenContent`, does it?

**Comment by leo-beliakov** [comment]
Facing the same issue
