### ISSUE TITLE
Google-Mobile-Ads-SDK v8.4.0 and previous versions has been refused by AppStore!!!

### ISSUE THREAD

**Issue by Joyeye** [googleads/googleads-mobile-ios-examples#223]
"ITMS-90809: Deprecated API Usage — Apple will stop accepting submissions of apps that use UIWebView APIs"

**Comment by Joyeye** [comment]
Dear Sir/Madam,  I have embedded the newest Google-Mobile-Ads-SDK v8.4.0 into my iOS app. However, my app still was refused by AppStore due to the issue about UIWebView APIs. Please replace UIWebView with WKWebView ASAP, otherwise, any iOS apps with Google Mobile Ads SDK would be refused by AppStore again. Thanks!

**Comment by Joyeye** [comment]
I have verified the issue, and found that UIWebView has been removed from Google-Mobile-Ads-SDK v8.4.0. Closed!

**Comment by h576497619m** [comment]
i use commend "grep -n "UIWebView" -r ./"
the result have UIWebView
i use version is 8.4 and 8.13 to try
the commend return same result.

please help me, think you!

like this:
Binary file .//Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-arm64_x86_64-simulator/GoogleMobileAds.framework/GoogleMobileAds matches
Binary file .//Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-arm64_armv7/GoogleMobileAds.framework/GoogleMobileAds matches
