### ISSUE TITLE
cannot fetch the native ads in the NativeAds example

### ISSUE THREAD

**Issue by googoodalls** [googleads/googleads-mobile-ios-examples#23]
Hi, There,

I run this sample, can not get any ads.

is there anything wrong with the demo?

**Comment by temrich** [comment]
Hi, We recently released updates to our example apps. Can you please try again and see if you are still unable to see ads in our Native Advanced Example app?

Thank you!

**Comment by googoodalls** [comment]
Thank you, I forget to provide you the feedback.
the reason that I can not get the ad is that my native ads size is not in the correct range.
So thank you for your attention.

BR

Steven.C from Beijing, China
