### ISSUE TITLE
Integrating iOS Ad mob SDK in Chromium

### ISSUE THREAD

**Issue by shauket** [googleads/googleads-mobile-ios-examples#232]
Getting issue when i integrate for device and simulator, verified architecture that are correct.

Xcode 12.4

Target Platform: iOS Device and simulator

Undefined symbols for architecture x86_64:

  "___isPlatformVersionAtLeast", referenced from:

      -[APMMeasurement reportFirstOpenOnWorkerQueue] in GoogleAppMeasurement(APMMeasurement.o)

      -[APMIdentity iOS14OrAbove] in GoogleAppMeasurement(APMIdentity.o)

      -[APMSqliteStore prepareSQL:error:] in GoogleAppMeasurement(APMSqliteStore.o)

      +[APMDefaultIdentitySupport iOS14OrAbove] in GoogleAppMeasurement(APMDefaultIdentitySupport.o)

      l009 in GoogleMobileAds(GADNetwork.o)

      l011 in GoogleMobileAds(GADNetwork.o)

      l003 in GoogleMobileAds(GADDeviceOrientationSignalCache.o)

**Comment by ericleich** [comment]
This sounds like an issue that could be specific to your setup, not with one of the examples themselves. Please use the [developer forum](https://groups.google.com/g/google-admob-ads-sdk) for help diagnosing.
