### ISSUE TITLE
Google-Mobile-Ads-SDK 7.68.0 is broken as bintray is not available

### ISSUE THREAD

**Issue by murali-omio** [googleads/googleads-mobile-ios-examples#235]
### [REQUIRED] Step 1: Describe your environment

  * Google Mobile Ads Unity plugin version: 7.68.0
  * Platform: iOS
  * Platform OS version: iOS 14.5
  * Any specific devices issue occurs on: Cocoapod install
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

While trying to install Google-Mobile-Ads-SDK 7.68.0, it installs GoogleMobileAdsMediationFacebook 6.2.0.0 as a dependency which fails during `pod install`

Not able to reach this URL: [https://google.bintray.com/mobile-ads-adapters-ios/FacebookAdapter/6.2.0.0/FacebookAdapter-6.2.0.0.zip](https://google.bintray.com/mobile-ads-adapters-ios/FacebookAdapter/6.2.0.0/FacebookAdapter-6.2.0.0.zip)
<img width="571" alt="AdsSDK" src="https://user-images.githubusercontent.com/58173905/124618314-f94d4f80-de77-11eb-8d50-f5bc60902f79.png">

**Comment by satyamws** [comment]
@murali-omio Did you find any solution for this? I am also having the same issue.

**Comment by NVentimiglia** [comment]
If you are still experiencing this issue can you please open a case on the [google mobile ads support forum](https://groups.google.com/g/google-admob-ads-sdk)? Please include a network trace and device trace of the incident so we can look into this for you. If you can not replicate this issue on the test ad units, please include your app id and ad unit id as well.
