### ISSUE TITLE
Expanded example for GADNativeExpressAdView

### ISSUE THREAD

**Issue by ed-mejia** [googleads/googleads-mobile-ios-examples#24]
Hi Guys, could you please improve the samples for GADNativeExpressAdView, the actual example it's really a "hello world" type... for example We are having issues trying to put the view into a collection view or table view, please refer to this SO question [GADNativeExpressAdView](http://stackoverflow.com/questions/37846820/admob-native-expess-ads-blocks-while-scrolling-in-uicollectionview/37862321#37862321) mainly because the Ad blocks the main thread while scrolling. 

What should be the right approach when including GADNativeExpressAdView in this type of scenarios?

Thanks!

**Comment by alokfuterox** [comment]
I got same issue 
Please help me out.

Regard
Alok

**Comment by ed-mejia** [comment]
The response time to address reports like this is shameful coming from google ... 👎

**Comment by temrich** [comment]
We really appreciate your feedback on improving our iOS example apps and definitely apologize for the delay.

We are currently working on adding a table view example app for native express ads and our goal is to release it in the upcoming months.

**Comment by temrich** [comment]
We just added a Native Express RecyclerView example app to our Android GitHub repo: https://github.com/googleads/googleads-mobile-android-examples/tree/master/advanced/NativeExpressRecyclerViewExample

iOS version is currently being built and will hopefully have it out shortly. Thanks again for your patience!

**Comment by francesc-o** [comment]
Are there any news about this request after 3 months? Thanks

**Comment by temrich** [comment]
We just added Native Express UITableView example apps for both Swift and Objective-C.

**Comment by patelmonika006** [comment]
@ed-mejia  U know, how to bind native express ads in uitableview???

**Comment by patelmonika006** [comment]
@temrich    U know, how to bind native express ads in uitableview???

**Comment by ericleich** [comment]
@patelmonika006 The native express ads in UITableView demo is [here](https://github.com/googleads/googleads-mobile-ios-examples/tree/master/Objective-C/advanced/NativeExpressTableViewExample).

**Comment by patelmonika006** [comment]
Alreday I checked this demo
is there no example which display ads in tableview

**Comment by patelmonika006** [comment]
yes I got the demo

**Comment by patelmonika006** [comment]
Is there any way, to hide demo "close" ads button
Please see my screen shot
[image: Inline image 2]

**Comment by ericleich** [comment]
@patelmonika006 sorry for the delayed response. The screenshot you posted didn't show up here on GitHub, so I'm not sure what you're asking.
