### ISSUE TITLE
Fatal Exception: UIApplicationInvalidInterfaceOrientation Supported orientations has no common orientation with the application, and [GADFullScreenAdViewController shouldAutorotate] is returning YES

### ISSUE THREAD

**Issue by vishalrana-spaceo** [googleads/googleads-mobile-ios-examples#247]
The app is crashing on iPad only. 
I am using latetst version of SDK 8.10.0

**Comment by mahaghanemamer** [comment]
Do you found a solution? @vishalrana-spaceo

**Comment by JillSong** [comment]
If you still encounter the issue with our latest SDK feel free to reopen the thread with steps to reproduce
