### ISSUE TITLE
SDK conflicts caused a crash

### ISSUE THREAD

**Issue by dota2AndTI** [googleads/googleads-mobile-ios-examples#249]
In podFile
pod 'BaiduMapKit','6.3.1'
pod 'Google-Mobile-Ads-SDK','8.8.0'

map = [[BMKMapView alloc] initWithFrame:self.view.bounds];
crash:
malloc: *** error for object 0xfffffffc00000004: pointer being freed was not allocated
malloc: *** set a breakpoint in malloc_error_break to debug

**Comment by NVentimiglia** [comment]
Hi subratazee,

If you are still experiencing this issue can you please open a case on the [google mobile ads support forum](https://groups.google.com/g/google-admob-ads-sdk)? Please include a network trace and device trace of the incident so we can look into this for you. If you can not replicate this issue on the test ad units, please include your app id and ad unit id as well.
