### ISSUE TITLE
My ads don't work on real devices

### ISSUE THREAD

**Issue by dms90** [googleads/googleads-mobile-ios-examples#25]
Hi there,

I can see ads working properly on simulator or testing device but not on a real device.

The app was approved and it is on the AppStore.

Here is the code I'm using.

```
print("Google Mobile Ads SDK version: " + GADRequest.sdkVersion())
let request = GADRequest()
request.testDevices = ["XXXXXXX", kGADSimulatorID]        
bannerView.adUnitID = "ca-app-pub-XXXXXX/YYYYY"
bannerView.rootViewController = self
bannerView.loadRequest(request)
```

Do you have any idea?

Thanks and regards!

**Comment by ericleich** [comment]
The code you have here looks ok.

Check the ad unit settings for that ad unit you're using. Any chance it was created for some ad type other than banner?

**Comment by dms90** [comment]
Thanks @ericleich for the answer! It was that.. I was using native ads instead of banner.

Thanks!

**Comment by ericleich** [comment]
Great! Glad to hear you were able to resolve it.
