### ISSUE TITLE
Memory Leak occurs in Google-Mobile-Ads-SDK (8.13.0) - iOS

### ISSUE THREAD

**Issue by Sunrise17** [googleads/googleads-mobile-ios-examples#259]
After i have updated to latest pods in my project, WKHoverPlatter leaks as soon as ad has been loaded during the launching of the app.

<img width="1423" alt="Google_Mobile_Ads" src="https://user-images.githubusercontent.com/26038249/146428681-1645a228-ae96-4a26-84ad-542792c30078.png">

I have disabled following codes as follows, leak has gone.
`GADMobileAds.sharedInstance().start(completionHandler: nil)`
`let request = GADRequest()`
`GADRewardedAd.load(withAdUnitID: gainCoinAdId, request: request) { (ad, error) in ... }`

**Comment by ericleich** [comment]
The Google Mobile Ads SDK uses WKWebView to serve ads, but the leak is happening within WKWebView. This same leak happens in a test app that uses WKWebView and does not use the Google Mobile Ads SDK.

For what it's worth, the leak is small (96 bytes).
