### ISSUE TITLE
GoogleMobileAds - Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by LudaFuxPlaybuzz** [googleads/googleads-mobile-ios-examples#26]
Since I've added GoogleMobileAds (Interstitial or Banner) I have the following error popping out all the time. 
`Command failed due to signal: Segmentation fault: 11`
What is going on??

**Comment by temrich** [comment]
Hi, 
The GitHub issue tracker is for issues or feature requests for our example apps only.

Please visit our [support forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk) to browse previous issues or report SDK issues/bugs.
