### ISSUE TITLE
Can you guys create examples for SwiftUI iOS Applications?

### ISSUE THREAD

**Issue by asolanki-in** [googleads/googleads-mobile-ios-examples#266]
I couldn't find a good example to implement ads in SwiftUI app natively. I don't want to use UIViewRepresentable.

**Comment by FelixKAcheampong** [comment]
Yes me too

**Comment by diamont1001** [comment]
+1

**Comment by sjvc** [comment]
+1

**Comment by malandr2** [comment]
Happy to share we have just released our [SwiftUI sample app](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Swift/advanced/SwiftUIDemo)
