### ISSUE TITLE
Google Video Ad issue

### ISSUE THREAD

**Issue by subratazee** [googleads/googleads-mobile-ios-examples#273]
Google video ads are not playing in iO versions lesser than 14. Video is getting stuck.

**Comment by NVentimiglia** [comment]
Hi subratazee,

If you are still experiencing this issue can you please open a case on the [google mobile ads support forum](https://groups.google.com/g/google-admob-ads-sdk)? Please include a network trace and device trace of the incident so we can look into this for you. If you can not replicate this issue on the test ad units, please include your app id and ad unit id as well.
