### ISSUE TITLE
How to enable location services

### ISSUE THREAD

**Issue by zigatartara** [googleads/googleads-mobile-ios-examples#28]
Hello,

I have some difficulties with enabling location services in SDK. I don't have any option to Allow user location or ask to allow for when I check possible permissions in settings for this app. I tried with adding location-services in Info.plist file like it is mentioned on https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html  but it didn't work for me. Do you have any additional info how to include option to share location.

Thanks

**Comment by temrich** [comment]
Hi, you may want to checkout the Info.plist that we use for our API Demo app, it might help you get set up with enabling permissions for location services: https://github.com/googleads/googleads-mobile-ios-examples/blob/master/Objective-C/advanced/APIDemo/APIDemo/Info.plist#L30

and here's the implementation: https://github.com/googleads/googleads-mobile-ios-examples/blob/master/Objective-C/advanced/APIDemo/APIDemo/AdMobAdTargetingTableViewController.m#L112
