### ISSUE TITLE
Interstitial ad - GADMobileAds.applicationMuted isn't working as expected

### ISSUE THREAD

**Issue by StevenChenAlfred** [googleads/googleads-mobile-ios-examples#293]
This is can be reproduced by replacing the unit id with `ca-app-pub-3940256099942544/8691691433` which is from
https://developers.google.com/admob/android/test-ads

The ad sound still play out even if `GADMobileAds.sharedInstance().applicationMuted = true` before load Ad

**Comment by NVentimiglia** [comment]
Closing this issue because it is almost a year old. Please reopen if you are still experiencing this issue.
