### ISSUE TITLE
Data Disclosure Documentation is unclear

### ISSUE THREAD

**Issue by under3415** [googleads/googleads-mobile-ios-examples#294]
[Prepare for Apple's App Store data disclosure requirements](https://developers.google.com/admob/ios/data-disclosure) documentation is unclear.

For each of the relevant data usage scenarios, Apple requires us to specify if data is:
1. Linked to the user's identity and
2. Used for tracking purposes

The above document specifies that "crash data" is "non user related", and that "performance data" is "user associated", but for the other ones it does not say.

Can you please specify for each of the following scenarios if data is linked to user's identity:

1. IP address (a.k.a. coarse location)
2. Device ID
3. Advertising Data
4. Product Interactions
5. Crash Data (not linked?)
6. Performance Data (is linked?)

Also, can you specify which ones of the above six data scenarios are used for "tracking purposes".

This [online article](https://levelup.gitconnected.com/filling-out-the-app-privacy-section-in-app-store-connect-for-admob-users-bca0768ad86e) attempts to interpret your document, but I worry that the interpretation is too strict, i.e., it assumes that you are tracking and linking user's identity when it was not specified otherwise. This may very well be true, but would be good for Google to clarify so that we are not providing incorrect information.

Thanks

**Comment by ericleich** [comment]
We can't comment more specifically than what is already on the data disclosure guides, but note per updates to that page that we do plan to support Apple's privacy manifest files.

Closing the issue here as it's not related to the iOS sample projects.
