### ISSUE TITLE
Umbrella header does not include header 'GADNativeAdCustomClickGestureOptions.h'

### ISSUE THREAD

**Issue by saldous** [googleads/googleads-mobile-ios-examples#296]
GoogleMobileAds 9.12.0 Xcode build warning:

`Umbrella header for module 'GoogleMobileAds' does not include header 'GADNativeAdCustomClickGestureOptions.h'`

<img width="1516" alt="image" src="https://user-images.githubusercontent.com/3334306/198112406-a2036554-f697-4a91-8695-2facca1fd0a9.png">

**Comment by ericleich** [comment]
Thanks for the report, I've filed a bug internally for this.

**Comment by minhdanh** [comment]
Not sure if it's related but I'm using Flutter. After upgrading to latest google_mobile_ads package (2.2.0 - which seems to use GoogleMobileAds 9.12.0), I cannot build iOS package anymore because of this error:
```
Swift Compiler Error (Xcode): Using bridging headers with module interfaces is unsupported
```

**Comment by ericleich** [comment]
The SDK header fix will go out in the next SDK release. I'm not sure of the Flutter-specific error though, for that I suggest filing an issue on the Flutter issue tracker at https://github.com/googleads/googleads-mobile-flutter/issues.

**Comment by minhdanh** [comment]
Thanks @ericleich. I reported the Flutter issue here: https://github.com/googleads/googleads-mobile-flutter/issues/686

**Comment by malandr2** [comment]
Closing as this issue as been resolved with the iOS SDK and the Flutter plugin
