### ISSUE TITLE
native ad crash

### ISSUE THREAD

**Issue by MaricleZhang** [googleads/googleads-mobile-ios-examples#299]
[admob_native_ad_crash.txt](https://github.com/googleads/googleads-mobile-ios-examples/files/9957303/admob.2022-11-8.11-02.txt)

**Comment by JillSong** [comment]
Hey @MaricleZhang, if you encounter crash due to our SDK, please post the our support forum https://groups.google.com/g/google-admob-ads-sdk and we will take a look because we can't take private information on gitHub. Thanks!
