### ISSUE TITLE
Module 'GoogleMobileAds' not found

### ISSUE THREAD

**Issue by ranjitk-plackal** [googleads/googleads-mobile-ios-examples#3]
When I try to run the sample app for Interstial Ad, I get error as below

Module 'GoogleMobileAds' not found for line @import GoogleMobileAds;

Regards
Ranjit

**Comment by ericleich** [comment]
In your projects build settings, search for `Modules`, and find the  `Enable Modules` setting. This will need to be set to `YES` for modules to be recognized.
