### ISSUE TITLE
IOS 16 devices:  Banners and interstitial ads cannot be displayed

### ISSUE THREAD

**Issue by G0561** [googleads/googleads-mobile-ios-examples#300]
Hello everybody

When my own ios app was upgraded to 16.x, banners and interstitials didn't show up. I downloaded admob's official banner and interstitial code, ran it with xcode and found that the ads could not be displayed (no error), I hope you can come out and discuss, thank you

masos: ventura 13.0.1
xcode: 14.1
ios: 16.1.1 (ipad, iphone14 and so on)
Google Mobile Ads SDK: The latest Version

**Comment by G0561** [comment]
This is a very serious bug, hope the authorities can pay attention to it

**Comment by NVentimiglia** [comment]
Closing this issue because it is almost a year old. Please reopen if you are still experiencing this issue.
