### ISSUE TITLE
IOS This method should not be called on the main thread as it may lead to UI unresponsiveness.

### ISSUE THREAD

**Issue by sdengaev** [googleads/googleads-mobile-ios-examples#317]
After launch, this error appears and the application crashes:
This method should not be called on the main thread as it may lead to UI unresponsiveness.
SDK 10.0.0

**Comment by sdengaev** [comment]
?

**Comment by sdengaev** [comment]
?

**Comment by sdengaev** [comment]
> Seems like randomly freezing the app.

app store doesn't let this app pass

**Comment by neobie** [comment]
> 

I passed but seems to have random hanging issue.

**Comment by leewonghao** [comment]
I have same issue!

**Comment by joshh-devrel** [comment]
Closed as the issue wasn't reproducible, please update to use the [latest GMA SDK version](https://developers.google.com/admob/ios/rel-notes). If the issue still persists, you can [contact](https://developers.google.com/admob/ios/support) Google Mobile Ads SDK support and provide sample project and complete stack trace/ crash logs that can help with the investigation.

**Comment by joshh-devrel** [comment]
Closed as the issue wasn't reproducible, please update to use the [latest GMA SDK version](https://developers.google.com/admob/ios/rel-notes). If the issue still persists, you can [contact](https://developers.google.com/admob/ios/support) Google Mobile Ads SDK support and provide sample project and complete stack trace/ crash logs that can help with the investigation.
