### ISSUE TITLE
DFP interstitial Ads size

### ISSUE THREAD

**Issue by DinaHussieny** [googleads/googleads-mobile-ios-examples#32]
DFP interstitial Ad doesn't appear with its correct size, it doesn't fit the screen the add appear to be smaller than screen width and height.
the ad unit ID "/1017609/mobileapp_interstitial"
![4fbaf93c-6257-11e6-8a53-b0a91bd066f1](https://cloud.githubusercontent.com/assets/16018799/18032854/e0eb2b18-6d13-11e6-94fb-14b55320659e.png)

**Comment by temrich** [comment]
Hi, are you able to reproduce this with our DFP Interstitial example app? If so, can you please direct this to the Mobile Ads SDK developer forum that we have linked in the README (https://github.com/googleads/googleads-mobile-ios-examples/blob/master/README.md).
Thank you!
