### ISSUE TITLE
Question on Sample

### ISSUE THREAD

**Issue by chitgoks** [googleads/googleads-mobile-ios-examples#320]
my ad view component looks like this
```
struct AdView: UIViewRepresentable {
    var unitID: String

    func makeCoordinator() -> Coordinator {
        return Coordinator()
    }

    func makeUIView(context: Context) -> GADBannerView {
        let adView = GADBannerView(adSize: GADAdSizeBanner)
        let frame = adView.frame.inset(by: adView.safeAreaInsets)
        let viewWidth = frame.size.width
        adView.adUnitID = unitID
        adView.rootViewController = UIApplication.shared.getRootViewController()
        adView.adSize = GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth(viewWidth)
        adView.load(GADRequest())
        return adView
    }

    func updateUIView(_ uiView: GADBannerView, context: Context) {

    }

    class Coordinator: NSObject, GADBannerViewDelegate {
        func bannerViewDidReceiveAd(_ bannerView: GADBannerView) {
            print("bannerViewDidReceiveAd")
        }

        func bannerView(_ bannerView: GADBannerView, didFailToReceiveAdWithError error: Error) {
            print("bannerView:didFailToReceiveAdWithError: \(error.localizedDescription)")
        }

        func bannerViewDidRecordImpression(_ bannerView: GADBannerView) {
            print("bannerViewDidRecordImpression")
        }

        func bannerViewWillPresentScreen(_ bannerView: GADBannerView) {
            print("bannerViewWillPresentScreen")
        }

        func bannerViewWillDismissScreen(_ bannerView: GADBannerView) {
            print("bannerViewWillDIsmissScreen")
        }

        func bannerViewDidDismissScreen(_ bannerView: GADBannerView) {
            print("bannerViewDidDismissScreen")
        }
    }
}
```

the ad size is 320x50
but when it is loaded, it looks like this. why is that?

![Simulator Screen Shot - iPhone 14 Pro - 2023-03-07 at 21 19 07](https://user-images.githubusercontent.com/3955470/223433734-c6d00446-c133-47ec-bf52-48900b4724bb.png | width=300)

and the code looks like this
```
var body: some View {
        NavigationStack(path: $appData.path) {
            VStack {
                ZStack(alignment: .leading) {
                    ......
                }

                AdView(unitID: "*****************************")
                    .background(.red)
            }
            .navigationBarHidden(true)
        }
        .navigationViewStyle(.stack)
        .environmentObject(appData)
    }
```

If i set the Adview with .frame(height: 50) then it works but this is not the right way to go. Why is the height large? What do you think could be lacking so that its frame will respect whats adSize is?

I tried to console.out these

```
func bannerViewDidReceiveAd(_ bannerView: GADBannerView) {
            print("bannerViewDidReceiveAd")
            print(bannerView.adSize.size.width)
            print(bannerView.adSize.size.height )
        }
```

And the height changes. weird. what could be the problem?

**Comment by ericleich** [comment]
@malandr2 can you answer this?

One thing to note is that if the adView's frame size changes at any point, the SDK will reload an ad whose ad size matches that new frame. I couldn't immediately tell from this sample code that the frame is getting set to 300x250 anywhere though.

**Comment by malandr2** [comment]
Hi @chitgoks,

Can you provide a minimum reproducible sample of the issue that you are observing? We also have documentation for [Banner ads](https://developers.google.com/admob/ios/swiftui#banner) that may be useful for you. Try following the documentation and apply it to your case and see if that resolves your issue.

**Comment by malandr2** [comment]
Closing this issue out, if you are still experiencing this issue or have further questions please post to the [AdMob Developer Forum](https://groups.google.com/g/google-admob-ads-sdk)
