### ISSUE TITLE
Unauthorized analytics collection by default

### ISSUE THREAD

**Issue by FineTillYouCameAlong** [googleads/googleads-mobile-ios-examples#336]
On startup I'm getting:
```
<Google>[I-ACS025031] AdMob App ID changed. Original, new: (nil), ca-app-pub-******
<Google>[I-ACS023007] Analytics v.100600000 started
<Google>[I-ACS023012] Analytics collection enabled
```
How do I disable this default behavior? I don't want this analytics collection before the user has agreed to it.
I am not using Firebase but nevertheless I tried putting the following in `Info.plist` to no effect:
```
<key>FIREBASE_ANALYTICS_COLLECTION_ENABLED</key>
<false/>
<key>FirebaseDataCollectionDefaultEnabled</key>
<false/>
```

**Comment by ericleich** [comment]
You are probably looking for https://developers.google.com/admob/ios/privacy/gdpr#delay_app_measurement.

**Comment by ericleich** [comment]
Please also note that for general support questions on the Google Mobile Ads SDK, the intended support channel is the https://groups.google.com/group/google-admob-ads-sdk forum. This issue tracker is intended for bugs in the samples themselves.
