### ISSUE TITLE
Undefined symbols: _SKStoreProductParameterAdNetworkSourceIdentifier

### ISSUE THREAD

**Issue by Spatel91111** [googleads/googleads-mobile-ios-examples#339]
Getting below issue

Undefined symbols for architecture arm64:
  "_SKStoreProductParameterAdNetworkSourceIdentifier", referenced from:
      l030 in GoogleMobileAds(GADInAppStoreMonitor.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Xcode 14.0
Mac OS : Monterey 12.6.1
Chip : M2
Google-Mobile-Ads-SDK : 10.6.0

**Comment by bharat-brainvire** [comment]
<img width="1206" alt="Screenshot 2023-06-14 at 3 18 05 PM" src="https://github.com/googleads/googleads-mobile-ios-examples/assets/136059747/b9e867e7-d970-4886-9037-d6682a5b1ff5">


But, You can use to resolve above issue.
pod 'Google-Mobile-Ads-SDK', '10.3.0'

**Comment by Spatel91111** [comment]
Thanks @bharat-brainvire , it help to resolve the issue.
