### ISSUE TITLE
Support Swift 3.0 and Xcode 8.0 with cocoapods?

### ISSUE THREAD

**Issue by androidcn** [googleads/googleads-mobile-ios-examples#34]
Support Swift 3.0 and Xcode 8.0 with cocoapods?

**Comment by temrich** [comment]
Hi, we just updated our Swift example apps to support Swift 2.3. You should be able to open and run the apps in Xcode 8.

**Comment by temrich** [comment]
We just released updated Swift example apps that support Swift 3.
