### ISSUE TITLE
Pod install is not working

### ISSUE THREAD

**Issue by fengxing1** [googleads/googleads-mobile-ios-examples#35]
Error installing Firebase，
[!] /usr/bin/curl -f -L -o /var/folders/4r/b0y15zhs4mgfvkz6jsx7yvp00000gn/T/d20160926-21140-3ekvk9/file.tgz https://www.gstatic.com/cpdc/cc5f7aac07ccdd0a/Firebase-3.5.0.tar.gz --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0curl: (7) Failed to connect to www.gstatic.com port 443: Operation timed out

in china！

**Comment by temrich** [comment]
We just pushed an update to our Podfile.lock files. Please try again and let us know if you are still running into an issue with pod install.

**Comment by TimaSp** [comment]
The same problem! I dont know what to do :(

**Comment by temrich** [comment]
Which example app are you trying to run pod install on? Can you provide the output when you run "pod install" or "pod update?"
