### ISSUE TITLE
Can't close AdMob Reward, iOS Safearea issue 

### ISSUE THREAD

**Issue by llmagicll** [googleads/googleads-mobile-ios-examples#359]
### Issue:
Incorrect Safe Area Layout in Some Reward Templates

### SDK Version Tested
Latest iOS SDK for versions 10.9 and 10.7

### Description
Certain reward templates display an incorrect safe area layout. This results in layouts that intersect the status bar and cannot be closed.

### Screenshot of correct safe area layout
![image](https://github.com/googleads/googleads-mobile-ios-examples/assets/2182193/c008d139-6dd3-4a79-8cc9-51e79caeb1e8)

### Screenshot of incorrect safe area layout

![image](https://github.com/googleads/googleads-mobile-ios-examples/assets/2182193/cda322fb-c92c-4a30-bc89-b04187b279bd)

![image](https://github.com/googleads/googleads-mobile-ios-examples/assets/2182193/1903a4d3-3480-48da-82dc-7293156c1c30)

**Comment by NVentimiglia** [comment]
Hi,

This is an issue with the specific rewarded ad creative and this repository is specific to the Admob samples. 

Please report this issue to the [Admob Sdk Forum](https://groups.google.com/g/google-admob-ads-sdk). Please include a charles log as those point to the reward templates with the issue.
