### ISSUE TITLE
AdChoices overlay is missing

### ISSUE THREAD

**Issue by weakfl** [googleads/googleads-mobile-ios-examples#36]
Try the 'DFP Custom Rendering Example' and request a content ad.
AdChoices overlay is missing...

![simulator screen shot 12 10 2016 13 21 23](https://cloud.githubusercontent.com/assets/614985/19308257/06dd405c-907f-11e6-85f7-71acc579ef6a.png)

**Comment by ericleich** [comment]
This is working as intended, and it is related to the way that particular creative is set up. This is set up as a direct-sold creative in DFP, and not AdExchange backfill. For DFP direct-sold inventory AdChoices is not there because the ad is the publisher's ad they set up, not a "Google" ad.
