### ISSUE TITLE
Ad Inspector Error: Ad Inspector closed unexpectedly

### ISSUE THREAD

**Issue by F170x** [googleads/googleads-mobile-ios-examples#360]
I've just updated to **Google Mobile Ads SDK 10.9.0** (updating from `9.14.0` with zero issues) and now I'm getting an alert in my app with the following message:

> **Ad Inspector Error** 
> Ad Inspector closed unexpectedly.

![alert](https://github.com/googleads/swift-package-manager-google-mobile-ads/assets/69001223/a3a3167c-cf52-435d-b343-88623de96833)

I never fire the function to open the Ad Inspector
The device is not in _Test devices_ in the admob console
I don't know how to reproduce it, I just updated and now I'm getting that alert on my app randomly a couple of times per day.

Environment:
- iPhone 14 Pro
- iOS 16.6
- Google Mobile Ads SDK 10.9.0

I think that it could be related to the update 10.8.0 that says in release notes:
> Ad inspector now displays the error that occurred when the session fails to start.

Release notes: https://developers.google.com/admob/ios/rel-notes

I downgraded to 10.7.0 and the errors gone

**Comment by NVentimiglia** [comment]
Hi,

This is an issue with the specific rewarded ad creative and this repository is specific to the Admob samples. 

Please report this issue to the [Admob Sdk Forum](https://groups.google.com/g/google-admob-ads-sdk). Please include a charles log and a device log, and we will see what we can do.
