### ISSUE TITLE
 Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by JRJian** [googleads/googleads-mobile-ios-examples#361]
<img width="1248" alt="image" src="https://github.com/googleads/googleads-mobile-ios-examples/assets/8022148/89d4a268-e584-43c9-895b-4bca627b62a6">
BannerAd code crash

**Comment by NVentimiglia** [comment]
Testing the [Banner Example](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Objective-C/admob/BannerExample) I did not replicate this bug.

I think this code may be in your custom implementation, but it is hard to tell from such a small snippet. Please double check your implementation and diff it with the linked sample. If you still have issues please reopen and reach out.

**Comment by JRJian** [comment]
It's my problem, i didn't instantiate bannerView. Sorry!
