### ISSUE TITLE
Network request failed   

### ISSUE THREAD

**Issue by Arya-Wang** [googleads/googleads-mobile-ios-examples#365]
Here are the relevant codes：
UMPConsentInformation.sharedInstance.requestConsentInfoUpdateWithParameters:completionHandler:
Network Request Return：
<img width="443" alt="image" src="https://github.com/googleads/googleads-mobile-ios-examples/assets/13763179/bbf12f96-6653-4e5b-8f5f-efd4ed4f326d">

China Network Access Interface Request Failed，Is there a solution？Thanks！

**Comment by NVentimiglia** [comment]
Hi @Arya-Wang 

Give us some time to look into this issue. I will let you know when we have next steps.
