### ISSUE TITLE
ios GADInterstitialAd endless call prefersStatusBarHidden

### ISSUE THREAD

**Issue by Toj-dev** [googleads/googleads-mobile-ios-examples#366]
hi,
I found a problem after running the demo
This is a demo
[InterstitialExample.zip](https://github.com/googleads/googleads-mobile-ios-examples/files/12508574/InterstitialExample.zip)

**Comment by NVentimiglia** [comment]
What is the problem? Can you include replication steps, a error log, and a brief description of the issue?

**Comment by Toj-dev** [comment]
If the prefersStatusBarHidden property is read endlessly, does it cause the program to stall?

**Comment by Toj-dev** [comment]
How can I cache this AD object without endlessly reading this attribute?

**Comment by NVentimiglia** [comment]
@Toj-dev 

Can you explain the problem in a few sentences with context of what you are trying to do, what you tried to do, what you expected to happen, and what happened? Please include a minimal code sample (e.g. 12 lines showing only the relevant code to what you are explaining) and I will be happy to help.

**Comment by Toj-dev** [comment]
![image](https://github.com/googleads/googleads-mobile-ios-examples/assets/43204431/c2a7f125-ebc8-4e85-9886-385c30388d10)

This is the log running on the iphone8Plus, Do not run on the emulator

![image](https://github.com/googleads/googleads-mobile-ios-examples/assets/43204431/b3f67a2c-67bb-46f5-a16f-b2671204f7a1)

Calling prefersStatusBarHidden endlessly

**Comment by Toj-dev** [comment]
This is demo

<img width="516" alt="image" src="https://github.com/googleads/googleads-mobile-ios-examples/assets/43204431/35ba9108-388e-4f79-bfa2-3b3242dc6601">

**Comment by NVentimiglia** [comment]
@Toj-dev 

I do not think this is related to the google mobile ads SDK. 

1) When I removed the google mobile ads sdk from the sample the prefersStatusBarHidden spam.

2) Looking at the stack trace, It looks like the caller is 

```
0x0000000127b51446 -[UIWindow _sceneSafeAreaInsetsIncludingStatusBar:] + 323", "7   UIKitCore            
```

I suggest you reach out to a iOS development group. If you can show me that this is caused by google mobile ads I will be happy to take another look.

**Comment by Toj-dev** [comment]
ok, thanks, I'll leave you a message if you have any questions
