### ISSUE TITLE
AdManagerMultipleAdSizesViewController not loading ads

### ISSUE THREAD

**Issue by sanimudah** [googleads/googleads-mobile-ios-examples#369]
I've run the test app and tried to see how the ads are handled for different size requests but it seems that the app is not showing the ads when different sizes are provided. I am getting the same behaviour in my own application as well. Is this broken at the moment?

<img src="https://github.com/googleads/googleads-mobile-ios-examples/assets/108250459/50dfb2c2-85ba-4b18-91d8-05510cd0ab0f" width=400></img>

**Comment by NVentimiglia** [comment]
Confirmed the issue, I will get this fixed.

Thank you!

**Comment by NVentimiglia** [comment]
@sanimudah 

The issue is now fixed, please try again.
