### ISSUE TITLE
Open ADs test mode always load fail.

### ISSUE THREAD

**Issue by iOS090Bravo** [googleads/googleads-mobile-ios-examples#379]
I tried to test open ads but the result when loading is:
App open ad failed to load with error: Ad unit doesn't match format. <https://support.google.com/admob/answer/9905175#4>
Before that I was still using it normally

**Comment by NVentimiglia** [comment]
@iOS090Bravo 

The ad unit Id we have listed is wrong. Please use `ca-app-pub-3940256099942544/5575463023` for App open ads.

**Comment by iOS090Bravo** [comment]
it worked, Thanks
