### ISSUE TITLE
ad is never ready

### ISSUE THREAD

**Issue by naeimsalib** [googleads/googleads-mobile-ios-examples#38]
i have this game and i created 3 funcions in my gameviewcontroller and here they are
    func getInterstitialAd(){
        interstitial = GADInterstitial(adUnitID: "ca-app-pub-1782852253088296/5018877964")
        let requestInterstitial = GADRequest()
        interstitial.load(requestInterstitial)
    }
    
    
    
    func showAd() {
        
        if (interstitial.isReady == true){
            interstitial.present(fromRootViewController: GameViewController())
        }else{
            print("ad wasn't ready")
            interstitial = createAd()
        }
        
        
        
    }
    
    func createAd() -> GADInterstitial{
        let interstital = GADInterstitial(adUnitID: "ca-app-pub-1782852253088296/5018877964")
        interstitial.load(GADRequest())
        return interstital
    }

and in one of my scene called StartMenu , i call those function
var viewController: GameViewController!

and then i call the functions 

           viewController.getInterstitialAd()
            viewController.showAd()

but it always returns ad not ready , and false for interstitial.isReady,
but also the getInterstitial function is always called .

can someone help with that please

**Comment by temrich** [comment]
Hi,
I was able to run our InterstitialExample app with Swift 3 and successfully display the interstitial ad.

It looks like it might be specific to your implementation. Can you provide the code to your GameViewController()? What class is the showAd() function in? What happens if you pass "self" to present(fromRootViewController:)?

**Comment by ericleich** [comment]
Closing due to 2 months of inactivity. Please reopen if this is still an issue.
