### ISSUE TITLE
Test Mode Label overlaps test ad banner dimensions

### ISSUE THREAD

**Issue by folsze** [googleads/googleads-mobile-ios-examples#384]
<img width="436" alt="image" src="https://github.com/googleads/googleads-mobile-ios-examples/assets/81622754/1144fb7f-c0fa-408f-a36e-26bd540a3af8">

As you can see here the test mode label overlaps the content of the admob ad. Specifially, it covers the middle part of the ad which reads out the dimensions of the ad actually. So one cannot tell the dimensions of the ad.

This is problematic for me, as I am currently facing a bug with the top banner height calculation of the https://github.com/capacitor-community/admob plugin, where a wrong height value is being returned. See this issue here:
https://github.com/capacitor-community/admob/issues/304

**Comment by malandr2** [comment]
Hi @folsze,

This issue appears to be related to our test ad unites and not an issue with one of our iOS samples. Please create a thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) for it to be adequately addressed. Closing this issue out - thanks!
