### ISSUE TITLE
Add privacy manifest

### ISSUE THREAD

**Issue by vinodram487** [googleads/googleads-mobile-ios-examples#385]
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by malandr2** [comment]
We are adding privacy manifest support in our version 11.0.0 release, coming early next year.

**Comment by jfoulkes23** [comment]
@malandr2 v11 has been released, does it contain the privacy manifest?

**Comment by KrisGeorgesKing** [comment]
Looking at 11.0.1, no PrivacyInfo.xcprivacy present 
<img width="457" alt="Screenshot 2024-03-03 at 10 28 35 PM" src="https://github.com/googleads/googleads-mobile-ios-examples/assets/159592849/0825903f-c26f-4ed2-8b79-0d531788f5f7">
