### ISSUE TITLE
sound/audio not coming in Rewarded ads using swift

### ISSUE THREAD

**Issue by Dev-iOS-Appbirds** [googleads/googleads-mobile-ios-examples#386]
sound/audio not coming in Rewarded ads using swift
Xcode version: 14.2

**Comment by malandr2** [comment]
Hi @Dev-iOS-Appbirds, 

This issue appears to be related to the ad creative and not an issue with one of our iOS sample. Please create a thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) for it to be adequately addressed. Closing this issue out - thanks!
