### ISSUE TITLE
iOS - GADRewardedAd.load block main thread when slow network

### ISSUE THREAD

**Issue by mandriao84** [googleads/googleads-mobile-ios-examples#389]
Hello,
GADRewrdedaAd.load method block the main thread in case of slow network.
I already run the method in the background thread and use async await func but it doesn't fix the freeze of the UI when facing slow network.
Regards.

**Comment by NVentimiglia** [comment]
Performance is a concern of ours and we will continue to make improvements. Please feel free to file a feature request to prioritize threading improvements over other feature enhancements [here](https://developers.google.com/admob/ios/support)
