### ISSUE TITLE
GADNativeExpressAdView

### ISSUE THREAD

**Issue by bernikowich** [googleads/googleads-mobile-ios-examples#39]
I've issue with memory leaks. Can you help me?
https://gist.github.com/bernikowich/52c95738c8f11e9f171ad22672af59fc

**Comment by temrich** [comment]
Are you seeing a memory leak with our NativeExpress sample app?

**Comment by ericleich** [comment]
Appears related to custom implementation and not the samples. Please raise this question on the [Google Mobile Ads SDK developer forum](http://groups.google.com/group/google-admob-ads-sdk).
