### ISSUE TITLE
Why do not have swift SDK? Please provide swift SDK, thanks

### ISSUE THREAD

**Issue by ghost** [googleads/googleads-mobile-ios-examples#4]

**Comment by ericleich** [comment]
Hi there,

The Mobile Ads SDK does work with Swift today. We don't have swift sample apps today to show off the usage, but that is on the roadmap.

**Comment by Babelfisch** [comment]
+1 Swift support

**Comment by DaRkD0G** [comment]
+1 Swift support

**Comment by RedBrogdon** [comment]
We've added Swift examples to the repo, so I'm going to go ahead and close this out.
