### ISSUE TITLE
Crash in GADJSONSafeDictionary

### ISSUE THREAD

**Issue by lionel-alves** [googleads/googleads-mobile-ios-examples#413]
Hi,

Please see the crash below, looks like a memory corruption issue.

Please fix, thanks!

<img width="1138" alt="image" src="https://github.com/googleads/googleads-mobile-ios-examples/assets/1184939/fdd3d14d-3bdf-419d-85de-8cf1b4e26b3e">

**Comment by NVentimiglia** [comment]
This repository is for the samples. Please file a bug report with the [SDK team](https://developers.devsite.corp.google.com/admob/support).
