### ISSUE TITLE
Undefined symbol: _GADUnifiedNativeIconAsset while migrating GoogleMobileAdsMediationFacebook with GoogleMobileAds iOS

### ISSUE THREAD

**Issue by 24Lathiya** [googleads/googleads-mobile-ios-examples#414]
I would like to migrate Facebook mediation with Google Mobile Ads.

```
pod 'Google-Mobile-Ads-SDK'
pod 'GoogleMobileAdsMediationFacebook'
```

Getting the below error after migrating to the latest version `11.2.0`.

`Undefined symbol: _GADUnifiedNativeIconAsset`

It is working fine if I downgrade pod to `pod 'Google-Mobile-Ads-SDK', '10.14.0'`

Kindly let me know if anyone has an idea to fix the above issue with the latest pod file.

**Comment by NVentimiglia** [comment]
This repository is for the samples. Please file a bug report with the [SDK team](https://developers.devsite.corp.google.com/admob/support).
