### ISSUE TITLE
Crash in GADSignals

### ISSUE THREAD

**Issue by lionel-alves** [googleads/googleads-mobile-ios-examples#415]
Hi,

Please see the crash below.

Please fix, thanks!

<img width="1117" alt="image" src="https://github.com/googleads/googleads-mobile-ios-examples/assets/1184939/4b2f68be-b53e-4adb-a44b-99e9a4b881e6">

**Comment by NVentimiglia** [comment]
This repository is for the samples. Please file a bug report with the [SDK team](https://developers.devsite.corp.google.com/admob/support).
