### ISSUE TITLE
library not found for -lGoogleToolboxForMac

### ISSUE THREAD

**Issue by Voidozzer** [googleads/googleads-mobile-ios-examples#42]
After installing pods build is failed with error 

> ld: library not found for -lGoogleToolboxForMac
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Using cocoapods-1.2.0.beta.1 (cocoapods-1.1.1 fails to generate pods project when installing pods)

**Comment by pom23** [comment]
Google

**Comment by temrich** [comment]
Hi, which example app are you seeing this error with? If you use the latest non-beta release of cocoapods, do you still see the issue?

**Comment by ericleich** [comment]
Closing due to lack of a response. Please reply if this is still an issue.

**Comment by karthisiva** [comment]
We are facing this issue after checkout from SVN.

1.Run pod install
2.Commit to repository
3.Delete local repository
4.Check out repository
5.Build project
6.Get error ld: framework not found GoogleMobileAds

My pod files looks like below:

target 'MMRevanp2016' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for MMRevanp2016
    pod 'libPusher', '~> 1.6.2'
    pod 'Google-Mobile-Ads-SDK'
    pod 'FBAudienceNetwork', '~> 4.24.0'
    pod 'KeychainItemWrapper'
    pod 'Vuukle', :git => 'https://github.com/vuukle/vuukle_iOS_SDK.git', :branch => 'swift_3'
    pod 'ATAppUpdater'
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end

**Comment by ericleich** [comment]
Hmm, still sounds like a git configuration issue. Do you have anything in your .gitignore that could prevent these depenencies from submitting?

Alternatively, after step 4, try running pod install again, and then run git diff. Did anything change? If so, then what's checked out of git in step 4 doesn't match the code you had in step 2.

**Comment by karthisiva** [comment]
Thanks for the reply. The problem was unfortunately we have added "Google-Mobile-Ads-SDK" both a way using pod and manual. By removing manually added framework, its work well. We Need to do clean once after removing sdk.
