### ISSUE TITLE
AppDelegate? For SwiftUI? Why?

### ISSUE THREAD

**Issue by Volodymyr-13** [googleads/googleads-mobile-ios-examples#423]
You should update examples for the latest SwiftUI which is NOT using old AppDelegate.
Stay updated!

**Comment by malandr2** [comment]
Hi @Volodymyr-13, please see our [SwiftUI demo](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Swift/advanced/SwiftUIDemo) which demonstrates a SwiftUI integration with the GMA SDK. We demonstrate how to use the `AppDelegate` as an example for logging purposes but it's not a requirement.
