### ISSUE TITLE
App open ad rendering issue

### ISSUE THREAD

**Issue by jsplashindia** [googleads/googleads-mobile-ios-examples#430]
Google-Mobile-Ads-SDK (11.5.0)
Device: iPhone 15

I am using the AppOpenExample provided under googleads-mobile-ios-examples. The only change I've done to the sample code is updating the GADApplicationIdentifier in Info.plist and the AdUnitID in the code with my values. Some of the app open ads with video, when rendered, the video appears outside the bounds of the ad. Please see the attached screenshots.

Portrait example 1:

![IMG_2653](https://github.com/googleads/googleads-mobile-ios-examples/assets/1921438/f172df33-9a84-4e3b-a4b7-cf5a3f6266d0)

Portrait example 2:

![IMG_2655](https://github.com/googleads/googleads-mobile-ios-examples/assets/1921438/1491929f-13e3-41d1-b30a-62e168e902d4)

Landscape example 1:

![IMG_2656](https://github.com/googleads/googleads-mobile-ios-examples/assets/1921438/54eef94f-36da-43f5-a6e2-53000c5786d5)

Landscape example 2:

![IMG_2657](https://github.com/googleads/googleads-mobile-ios-examples/assets/1921438/b3556b81-5478-4d74-b882-51ced286fde8)

**Comment by malandr2** [comment]
Hi @jsplashindia, the Google Mobile Ads SDK itself doesn't control the display of ad. Please create a new thread in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk) to properly address your issue. 

Closing this out. Thanks!
