### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by xxxxxxH** [googleads/googleads-mobile-ios-examples#432]
error: Sandbox: bash(2889) deny(1) file-write-create /Users/xxxxxxh/Desktop/workspace/iosVPn/DeterrenceEraVPN/Pods/resources-to-copy-DeterrenceEraVPN.txt (in target 'DeterrenceEraVPN' from project 'DeterrenceEraVPN')
/Users/xxxxxxh/Desktop/workspace/iosVPn/DeterrenceEraVPN/Pods/Target Support Files/Pods-DeterrenceEraVPN/Pods-DeterrenceEraVPN-resources.sh: line 20: /Users/xxxxxxh/Desktop/workspace/iosVPn/DeterrenceEraVPN/Pods/resources-to-copy-DeterrenceEraVPN.txt: Operation not permitted
Only one dependency was added： pod 'Google-Mobile-Ads-SDK'

**Comment by xxxxxxH** [comment]
Full access is enabled

**Comment by NVentimiglia** [comment]
Hi, It looks like you resolved this issue. Please reopen if the issue returns.
