### ISSUE TITLE
Build fail on XCode 15.0.1 and below - Google-Mobile-Ads-SDK (11.6.0)

### ISSUE THREAD

**Issue by abinhho** [googleads/googleads-mobile-ios-examples#433]
There are some reason I have to use **XCode 15.0.1** but could not build after update SDK to `11.6.0`

`XCode 15.2` and above build ok.

Logs

```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by NVentimiglia** [comment]
Hi @abinhho 

Required Minimum Xcode version is 15.3: https://developers.google.com/admob/ios/quick-start#prerequisites
