### ISSUE TITLE
Missing demo tableview banner ads

### ISSUE THREAD

**Issue by hoangnam714** [googleads/googleads-mobile-ios-examples#442]
Il semble que votre démo manque la démo de la bannière tableview, et pouvez également faire une démonstration d'annonces natives dans la tableview, merci.

**Comment by malandr2** [comment]
Hi @hoangnam714, please see the [InlineAdaptiveBannerExample](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Swift/advanced/InlineAdaptiveBannerExample) for banner ads in a `UITableView`. At this time we don't plan on adding a Native ad in a tableview but will monitor future requests. Thanks!
