### ISSUE TITLE
After added SDK via cocoa pods compilation issue 

### ISSUE THREAD

**Issue by Rohit737-star** [googleads/googleads-mobile-ios-examples#445]
Hello Team,

i have created demo project and added this library after added SDK project is not compiling . Even in your git demo project same issue after install pods sdk.

**I have xcode version 15.2**

getting error-

**Undefined symbols:
Linker command failed with exit code 1 (use -v to see invocation)**

here i have attached screenshot of issue.
<img width="1034" alt="Screenshot 2024-08-03 at 3 15 10 PM" src="https://github.com/user-attachments/assets/f2ce8f67-add5-4e02-a4da-e1d54f74ec56">

**Comment by Xa69** [comment]
Hi @Rohit737-star, just did a quick search online with this error message and have you tried this solution?

Similar issue : https://stackoverflow.com/questions/77139621/xcode-15-undefined-symbols-linker-command-failed-with-exit-code-1-use-v-to-s

**Comment by afskalsfk** [comment]
同样的问题遇到  用上述方法并没有解决

**Comment by afskalsfk** [comment]
> 大家好，
> 
> 我已经创建了演示项目，并在添加 SDK 项目后添加了此库，但无法编译。即使在您的 git 演示项目中安装 podsdk 后也存在同样的问题。
> 
> **我有 xcode 版本 15.2**
> 
> 出现错误-
> 
> **未定义符号： 链接器命令失败，退出代码为 1（使用 -v 查看调用）**
> 
> 这里我附上了问题的截图。 <img alt="截图于 2024-08-03 下午 3 点 15 分" width="1034" src="https://private-user-images.githubusercontent.com/54791283/354808759-f2ce8f67-add5-4e02-a4da-e1d54f74ec56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNTg1MjEsIm5iZiI6MTcyNzE1ODIyMSwicGF0aCI6Ii81NDc5MTI4My8zNTQ4MDg3NTktZjJjZThmNjctYWRkNS00ZTAyLWE0ZGEtZTFkNTRmNzRlYzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA2MTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYjhhZWRiY2IzNzQzYzdlYjBmODQ2OWMyYjQ2MWU2NGVmMmFkZjhiMjZhZmU5ZmIwYmEzOWViMDJjNDM0OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wFdl95ZQl0toVoKDkZnc2As9PKvQgb29PSP6J64NrvU">

请问你是怎么解决这个问题的

**Comment by malandr2** [comment]
Hi @Rohit737-star, to resolve this issue please create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk).

We recommend to also follow the [Get Started](https://developers.google.com/admob/ios/privacy) guide

**Comment by lennondong** [comment]
I had the same problem and searched for many options, none of which solved it. does the admob team not validate the SDK in Xcode when they roll it out?
