### ISSUE TITLE
SwiftUI - Interstitial Ad causing view disappearance when using a TextField after an interstitial is shown.

### ISSUE THREAD

**Issue by NickAtGit** [googleads/googleads-mobile-ios-examples#446]
There seems to be a bug with presenting an Interstitial Ad and then using a TextField afterwards. The problem is outlined here at Stackoverflow. A Rewarded Ad also produces that issue.

https://stackoverflow.com/questions/76463171/swiftui-interstitial-ad-causing-view-disappearance-when-returning-to-a-uitextf

Here is a video of how the issue looks:
https://x.com/dubdubcool/status/1820081138808865270

When deactivating interstitials everything is fine.

**Comment by NickAtGit** [comment]
I also found a workaround for that. When presenting the the ad on the topViewController (the rootViewController) this bug then appears later on in the app lifecycle. The workaround now is to present a dummy view with a ProgressView that then presents the ad. When the ad is dismissed also the dummy view is dismissed and the rest of the app stays functional.

**Comment by malandr2** [comment]
Hi @NickAtGit, for us to properly address your issue can you create a new thread in the [AdMob developers forum](https://groups.google.com/g/google-admob-ads-sdk)? From there we can begin the troubleshooting process. Closing this out as triaging will continue there. Thanks!

**Comment by NickAtGit** [comment]
Why making it so complicated? GitHub issues is the status quo. Why is Google not automatically creating these in their internal system? My time is also valuable... :/
