### ISSUE TITLE
In-app browser for banners

### ISSUE THREAD

**Issue by bulutoztemur** [googleads/googleads-mobile-ios-examples#447]
Hello,

Is it possible that when user clicks banner ad, we display it inside in-app browser?

**Comment by malandr2** [comment]
Hi @bulutoztemur, for us to properly assess your feature request, can you create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk)? From there, we can determine the next steps for your request. Closing this out - thanks!
