### ISSUE TITLE
GoogleMobileAds SDK shows the no signature message with the manual linking of frameworks to Libraries and Frameworks in the Xcode

### ISSUE THREAD

**Issue by jesphinpt** [googleads/googleads-mobile-ios-examples#458]
I am using the GoogleMobileAds SDK added in the app Manually, it shows the below message shall I add this to the app manually. Can anyone confirm shall i use this?

I have downloaded this from here
https://developers.google.com/admob/ios/download

<img width="503" alt="Screenshot 2024-08-28 at 5 27 38 PM" src="https://github.com/user-attachments/assets/fb44eae2-e90d-4a6c-890c-a54859eb5302">

**Comment by malandr2** [comment]
Hi @jesphinpt, per our release notes you can select "Accept Change": https://developers.google.com/admob/ios/rel-notes
