### ISSUE TITLE
Interstitial Ad Issue

### ISSUE THREAD

**Issue by developweb10** [googleads/googleads-mobile-ios-examples#46]
Getting this error every time, I added ATS privacy in plist file...

InterstitialExample[6790:2228703] CFNetwork SSLHandshake failed (-9806)
2017-04-11 16:31:39.331 InterstitialExample[6790] <Error> [Firebase/Core][I-NET901017] <Firebase/Network/ERROR> Encounter network error. Code, error: -1001, Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://play.googleapis.com/log, NSErrorFailingURLKey=https://play.googleapis.com/log, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.}

**Comment by ericleich** [comment]
The logs indicate the error is happening in Firebase/Core. Please reach out to the [Firebase forum](https://groups.google.com/forum/#!forum/firebase-talk) for help on this.

Alternatively, [Firebase is optional](https://firebase.google.com/docs/admob/admob-firebase#firebase_is_recommended_but_optional). You can instead recompile the app without Firebase with 3 quick changes:

1. Strip out the Firebase/Core and Firebase/AdMob pods in the [Podfile](https://github.com/googleads/googleads-mobile-ios-examples/blob/master/Objective-C/admob/InterstitialExample/Podfile#L6-L7) and replace with `pod Google-Mobile-Ads-SDK` and run `pod install` again.
2. In [AppDelegate.m](https://github.com/googleads/googleads-mobile-ios-examples/blob/master/Objective-C/admob/InterstitialExample/InterstitialExample/AppDelegate.m#L19), remove the `@import Firebase` and replace it with `@import GoogleMobileAds`
3. In [AppDelegate.m](https://github.com/googleads/googleads-mobile-ios-examples/blob/master/Objective-C/admob/InterstitialExample/InterstitialExample/AppDelegate.m#L31), remove the call to configure FIRApp.
