### ISSUE TITLE
Background Music Does Not Stop and Cannot Be Muted

### ISSUE THREAD

**Issue by make1a** [googleads/googleads-mobile-ios-examples#467]
We have received numerous complaints from users that background music in the app frequently does not stop and cannot be muted. After investigating, we have identified that the issue is caused by the Google Ads SDK version: Google-Mobile-Ads-SDK (11.3.0).

Key Points:

	1.	The background music is unexpected and uncontrollable — it should not be playing at all.
	2.	We have explicitly set the audio to mute in the SDK initialization code, but sound is still being played.
Code Example:
![img_v3_02et_4201c87d-36e7-4b0e-bfb2-f94bdbf274eg](https://github.com/user-attachments/assets/6ae03ef4-3fa3-45a4-9d29-700a83506b45)

Logs Captured:
```
[Voice Error] AVPlayer 开始播放 url = https://rr1---sn-jhi3-i3bd.googlevideo.com/videoplayback?expire=1726598347&ei=S1zpZuy1CcPRg8UP9ZmpuQM&ip=182.239.77.153&id=65348b6174597c58&itag=22&source=youtube&requiressl=yes&xpc=Eghovf3BOnoBAQ%3D%3D&mh=Rk&mm=31&mn=sn-jhi3-i3bd&ms=au&mv=m&mvi=1&pl=24&susc=gvp&acao=yes&ctier=L&mime=video%2Fmp4&vprv=1&rqh=1&dur=15.116&lmt=1725598813468100&mt=1726569181&cpn=IArBOuKEZO1yOlSq&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csusc%2Cacao%2Cctier%2Cmime%2Cvprv%2Crqh%2Cdur%2Clmt&sig=AJfQdSswRgIhANZI4Ll5-GknobGnOuf-YFOvDcGDUvje3-39OLiTKoDcAiEAzLPU7ZRAoDIufDdc5rcDZY4WJfjK2zQWdeKDCDCzUcs%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=ABPmVW0wRQIgf_TBHlvl1SOAeaOS8IsL2UKIXo04oFAge1Lb06bZeMMCIQDAtfffvDNjSwHxYvQtSk6rHTFpdgZ83Hp7HO_WWuNC1w%3D%3D&ic=gmasdk
```

We kindly ask for your assistance in addressing this issue as it negatively impacts user experience.

Let me know if you’d like to add more details or modify anything!

**Comment by malandr2** [comment]
Hi @make1a, please create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) so we can begin the troubleshooting process. Closing this out as triaging will take place in the forum. Thanks!
