### ISSUE TITLE
Rewarded Video - Let server know about reward

### ISSUE THREAD

**Issue by marioacarvalho** [googleads/googleads-mobile-ios-examples#47]
Hi,

I'm implementing rewarded videos on my app and I want to let server know about the reward.

How can I get an unique identifier of the reward? Or do you recommend any other safe option?

Thank you,
Mário

**Comment by ericleich** [comment]
AdMob as the network/mediation platform currently only supports client-side callbacks, not server-side callbacks.

If this is a hard requirement for you, the only option I can think of is to use another mediation platform to get AdMob ads. AdMob Rewarded video is also currently supported via [MoPub](https://www.mopub.com/resources/docs/android-sdk-integration/integrating-rewarded-video-android/) and [IronSource](http://developers.ironsrc.com/ironsource-mobile/android/admob-mediation-guide/#step-1) mediation platforms, and my understanding is both platforms support taking AdMob's client side callback and converting it into a server-side callback for you.
