### ISSUE TITLE
AdChoices overlay not shown

### ISSUE THREAD

**Issue by kolyuchiy** [googleads/googleads-mobile-ios-examples#5]
![simulator screen shot 19 oct 2015 19 06 31](https://cloud.githubusercontent.com/assets/898625/10601080/bac74bda-7717-11e5-930f-ca6ef136cd0e.png)
![simulator screen shot 19 oct 2015 19 06 54](https://cloud.githubusercontent.com/assets/898625/10601079/bac5902e-7717-11e5-81f5-7a0eeea46f58.png)

Instead I see circled i icon which I assume is not AdChoices overlay.
Tried both /6499/example/native and /6499/example/native-backfill unit IDs.

**Comment by RedBrogdon** [comment]
The overlay icon comes straight to the SDK from the server, so there's really nothing to it as far as the mobile code is concerned. It's possible that the serving team is playing around with new icons, as I'm still seeing the old one right now.

Thanks for checking on it, though. 

On an unrelated note, judging by the "destinationsforholidays" overlap in your screenshot, I need to alter the sample ad layout to better accommodate long advertiser strings.
