### ISSUE TITLE
No ad to show

### ISSUE THREAD

**Issue by KrifaYounes** [googleads/googleads-mobile-ios-examples#51]
I got this error message : Error Domain=com.google.ads Code=1 "Request Error: No ad to show." UserInfo={NSLocalizedDescription=Request Error: No ad to show., NSLocalizedFailureReason=Request Error: No ad to show.}

ios code :
    var nativeExpressAdView: GADNativeExpressAdView!

    func displayGoogleBanner() {
        var gadAdSize = GADAdSize()
        let size = CGSize(width: 280,height: 250)
        gadAdSize.size = size;
        
        self.nativeExpressAdView = GADNativeExpressAdView(adSize: gadAdSize, origin: CGPoint(x:
            ScreenSize.SCREEN_WIDTH/2 - 140, y: 10))
        self.contentView.addSubview(nativeExpressAdView)
        
        
        nativeExpressAdView.adUnitID = AppGame.googleNativeAdsBlocMappsGame
        nativeExpressAdView.rootViewController = self
        nativeExpressAdView.delegate = self
        
        let request : GADRequest = GADRequest()
        nativeExpressAdView.loadRequest(request)

    }

**Comment by ericleich** [comment]
Hi there,

Since this doesn't appear to be an issue with the sample apps themselves. I'm going to close this issue. Please ask your question in the [Google Mobile Ads SDK developer forum](//groups.google.com/group/google-admob-ads-sdk), and the support team there will be happy to help you out.

**Comment by 2819936788** [comment]
hi  i am error still ,when i   request GADRewardBasedVideoAd


 the error follow



Error Domain=com.google.ads Code=1 "Request Error: No ad to show." UserInfo={NSLocalizedDescription=Request Error: No ad to show., NSLocalizedFailureReason=Request Error: No ad to show.}
