### ISSUE TITLE
 Showing Recent Issues   "_OBJC_CLASS_$_GADInterstitial", referenced from:

### ISSUE THREAD

**Issue by zuojinmin** [googleads/googleads-mobile-ios-examples#53]
![image](https://user-images.githubusercontent.com/12218753/27743360-55c221aa-5dee-11e7-96b2-95571f697eb7.png)
![image](https://user-images.githubusercontent.com/12218753/27743369-5f5e0b48-5dee-11e7-9dfa-e32eec9be540.png)
@import GoogleMobileAds;
@interface ViewController111 ()
@property(nonatomic, strong) GADInterstitial *interstitial;
@end

@implementation ViewController111

- (void)viewDidLoad {
    [super viewDidLoad];
     [self createAndLoadInterstitial];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        if (self.interstitial.isReady) {
            [self.interstitial presentFromRootViewController:self];
        } 
    });
}
- (void)createAndLoadInterstitial {
    self.interstitial =
    [[GADInterstitial alloc] initWithAdUnitID:@"ca-app-pub-3940256099942544/4411468910"];
//    
    GADRequest *request = [GADRequest request];
    // Request test ads on devices you specify. Your test device ID is printed to the console when
    // an ad request is made.
    request.testDevices = @[ kGADSimulatorID, @"2077ef9a63d2b398840261c8221a0c9a" ];
    [self.interstitial loadRequest:request];
}

Showing Recent Issues
  "_OBJC_CLASS_$_GADInterstitial", referenced from:

      objc-class-ref in ViewController111.o

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ericleich** [comment]
How are you including the SDK? Are you dropping in GoogleMobileAds.framework into your app or are you using CocoaPods?

My guess is you imported in the framework manually, but you didn't check the `Copy items if needed` option. If you don't do that, Xcode doesn't set up the `Framework search paths` setting properly, and you get a linker error like this.

**Comment by ericleich** [comment]
Please reopen if this is still an issue.
