### ISSUE TITLE
Failed to load: Request Error: No ad to show.

### ISSUE THREAD

**Issue by allenwong** [googleads/googleads-mobile-ios-examples#54]
I have tried to use the sample adUnit ID in my app, it works very well, I can display the video ads from your server. This the sample ID I used: ca-app-pub-3940256099942544/1712485313. 

But I really need to try out my own adUnitID before I release it, yeah I just need to check it out, not click it. So I replace the adUnitID as my own. 

AppDelegate

`        GADMobileAds.configure(withApplicationID: "ca-app-pub-8783572725852328~7539766498")
`

HomeViewController

`   if !adRequestInProgress && rewardBasedVideo?.isReady == false {
            rewardBasedVideo?.load(GADRequest(), withAdUnitID: "ca-app-pub-8783572725852328/901649969")
            adRequestInProgress = true
        }`

Log

`Reward based video ad failed to load: Request Error: No ad to show.`

**Comment by ericleich** [comment]
I tried your ad unit and it works on my end.

When did you create the ad unit? It typically takes about an hour for newly created ad units to start serving?

**Comment by allenwong** [comment]
Hi @ericleich 
I also submit my issue on Google AdMob forum, they said I didn't fill any basic payment info, so I was going to fill it all.  Now everything is okay, I release it App Store yesterday.

**Comment by ericleich** [comment]
Glad to hear it's working for you!

**Comment by banupriyam** [comment]
Facing the same issue only on my live adUnitId "ca-app-pub-2205403669616327/4045941432" but development id is working fine. All clues are failed.
