### ISSUE TITLE
Request Error: No ad to show.

### ISSUE THREAD

**Issue by david-olaf** [googleads/googleads-mobile-ios-examples#58]
I can see Ad Banner when I test with test Ads. But I can't see anything when I remove test Ads. It prints the following log.

`adView:didFailToReceiveAdWithError: Request Error: No ad to show.`

Please help me. I can't find solution...

**Comment by 2819936788** [comment]
i am new ios version,has been add Google admob, but the version still reviewing

**Comment by ericleich** [comment]
Please reach out to the [Google Mobile Ads SDK developer forum](groups.google.com/group/google-admob-ads-sdk) regarding this issue, since it sounds like an issue with your ad unit/account rather than an issue with a sample app in this repo.

**Comment by heroims** [comment]
@ericleich .The same code in another project  is request success.Only in my old project request failed(Request Error: No ad to show.).Do you known maybe what happened?

**Comment by stowy** [comment]
Hi @heroims, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.  In this case, you'll need to provide more detail regarding the ad units that are failing to receive ads, our support forum will be able to guide you there. 

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
