### ISSUE TITLE
Ad info icon for content ad is not retina

### ISSUE THREAD

**Issue by kolyuchiy** [googleads/googleads-mobile-ios-examples#6]
![simulator screen shot 19 oct 2015 19 06 54](https://cloud.githubusercontent.com/assets/898625/10601137/249b7644-7718-11e5-9d72-a469c3e7e4d1.png)

**Comment by RedBrogdon** [comment]
I can definitely see the pixilation in your screenshot. As I said in response to your other issue, the icon comes straight down from the server, so I'd chalk this up to an experiment on their end.

That said, I'll pass your info along and make sure the right people see it. Thanks for posting it.
