### ISSUE TITLE
Sample Project has external dependency ?

### ISSUE THREAD

**Issue by cippyboy** [googleads/googleads-mobile-ios-examples#61]
Why does a "sample" project have external dependencies ? It's extremely frustrating. I don't intend on using cocoa pods in my project so why have a dependency that will not exist in many users' projects ?

**Comment by RedBrogdon** [comment]
CocoaPods isn't required to build and run any of the samples. If you don't wish to use it, simply delete the Podfile and lock, then [install the SDK directly](https://developers.google.com/admob/ios/quick-start#manual_download).

**Comment by cippyboy** [comment]
I did "install" the SDK, used "add files" to add the framework and then it says that the umbrella header can't be found. That's why I'm asking for something that unzips and compiles. For the past couple of updates I had to do extra work to make it compile, now it won't compile at all with Xcode 9.

**Comment by RedBrogdon** [comment]
I'm not sure why you're seeing an error, but I just verified that v7.24.1 of the SDK can be correctly linked into our Swift banner example by dragging it into the project and adding it to the list of linked binaries in the build phases settings.

If you'd like, you're welcome to bring this issue to the [AdMob SDK support forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk), where we have a team of support staff that can dig into your setup and find out what's going on.
