### ISSUE TITLE
Ads are shown only on XCode Simulator 

### ISSUE THREAD

**Issue by freek9807** [googleads/googleads-mobile-ios-examples#62]
My swift app shows ads on simulator but when I connect my iPad or another real device, there's no ad on the app and the debugger error is :

> adView:didFailToReceiveAdWithError: Request Error: No ad to show.

But on the Xcode simulator all is fine. This is my code :

```Swift
let request = GADRequest()  
banner.adUnitID = "/* My Secret Code */"  
banner.rootViewController = self  
banner.delegate = selfie  
 banner.load(request)
```

And in AppDelegate.swift : 

`GADMobileAds.configure(withApplicationID: "/* My Secret Code */")`

What can I do?

**Comment by stowy** [comment]
Hi, thanks for your query. In short, it looks like you need to set your device as a test device. Additionally, sometimes it takes time after having registered a new ad unit before ads will start serving for that ad unit. However you should [always test using test ads](https://developers.google.com/admob/ios/test-ads) (https://developers.google.com/admob/ios/test-ads). 

However, these github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
