### ISSUE TITLE
AdMob with ID belongs to user

### ISSUE THREAD

**Issue by xyzbilal** [googleads/googleads-mobile-ios-examples#64]
Hi There, 
I successfully implemented adMob bannerView to my project and  successfully see the indication that adMob shows when I use app id  and test ad unit ID given tutorials. but when I put my Id's to project. I dont get any indication that adMob works. I added my devise as testing device.  what can be the problem . here is the code what I write; 
 let request = GADRequest()
            request.testDevices = [ "97071aa9da3191dd1aa56c48741286dc" ]
            bannerView.adUnitID = "ca-app-pub-6385268451734532/7754086651"
            bannerView.rootViewController = self
            bannerView.load(request)

**Comment by stowy** [comment]
Hi, thanks for your query.

It sounds like you may have only recently created your ad unit, I advise waiting a little for it to be processed and then it will most likely work. Also, I recommend against publicly sharing your ad unit IDs.

Please not that in general, these github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Regards

Sam
