### ISSUE TITLE
The problem with Interstitial Ads

### ISSUE THREAD

**Issue by ChinhQT** [googleads/googleads-mobile-ios-examples#67]
Hi Google,

My application is applied on the portrait screen. But when I loaded the interstitial ads, the ads will be shown landscape without any the close button. How to fix the issues ? I've updated the lastest SDK.

![57a5f9b9-2d8e-439a-a41a-16105c8c40ab](https://user-images.githubusercontent.com/13697259/39171261-657995be-47c8-11e8-9ea3-3339d1b744b0.jpg)

**Comment by stowy** [comment]
Hi @ChinhQT , thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including steps showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
