### ISSUE TITLE
Project is not load properly.

### ISSUE THREAD

**Issue by WASIM654321** [googleads/googleads-mobile-ios-examples#68]
I can see some warning or error on git I am going to send you the screenshot of it please check, also after downloading the project its shows the bunch of errors.

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
