### ISSUE TITLE
Knock, knock, Does Reward Video blocked in China?

### ISSUE THREAD

**Issue by allenwong** [googleads/googleads-mobile-ios-examples#69]
Hi, Google AdMob Team, 
We are from China, and we face an issue for almost two weeks, which is our device can't load the reward video assets without VPN(Our user normal environment). If we turn on the VPN, add test device IDs at same time, Yes, it works perfectly, loaded the test videos record by your team. But Here is another issue that when we remove the test device id, it failed again, no video resources loaded.

So can you guys do me a little favor? Our ad unit id is `ca-app-pub-6744220399239276/5864391073`
could you test our id in your device?

Btw, Sorry in advance. I actually have written the email to your support team, and also wrote a post on the support forum, but no one responds, I can't figure out another way to reach your team, that's why I open an issue right here. 

Hope someone can help us and Thank you in advance.

**Comment by stowy** [comment]
Hi, it looks as though your account does have an active billing hold which would be why you are not seeing any ads.

It would be best if you contact AdMob product support using the [AdMob help center](https://support.google.com/admob/?hl=en#topic=7383088) as this issues is for issues with the sample app only, and yours is an account issue.

**Comment by allenwong** [comment]
@stowy anyway, thank you a lot!
