### ISSUE TITLE
Custom native ad is not working

### ISSUE THREAD

**Issue by kolyuchiy** [googleads/googleads-mobile-ios-examples#7]
Run DFPNativeExample project.
Check only Custom Native Ad switch on.
Tap Refresh Ad.

Result in console:
2015-10-20 10:49:48.339 DFPNativeExample[50671:32868793] <GADAdLoader: 0x7fa24db8bcb0> failed with error: Request Error: Received invalid response.

Nothing changes in app.

**Comment by RedBrogdon** [comment]
Hmm. I just checked this myself, and I did receive an ad. Can you give me some more information about what happened when you tried it? The SDK version, device details, and version of Xcode you used would be particularly helpful.

**Comment by kolyuchiy** [comment]
Today I updated to 7.5.2.
Here is the request/response: https://gist.github.com/kolyuchiy/108d09eb4116cbe1f75e
The device is iPhone 6 iOS 9.0 Simulator
Xcode Version 7.0.1 (7A1001)

Actually I've found why it was not working. It was because of this line which I added:
```
    request.testDevices = @[ kGADSimulatorID, @"45d25a1b52bb9c8fdef9fc1e6225704f" ];
```

After I removed it, custom native ad started showing up.

**Comment by RedBrogdon** [comment]
Ah, yes. The test ad system for native ads isn't as sophisticated (yet) as the one for banners and interstitials. It's mentioned at the bottom of our native ads guides:

https://developers.google.com/admob/ios/native
https://developers.google.com/mobile-ads-sdk/docs/dfp/ios/native

But we don't make a big enough deal out of it. 

I'm glad you were able to resolve your issue, though. Feel free to come by our developer forum (https://groups.google.com/forum/#!forum/google-admob-ads-sdk) if you run into any other issues.
