### ISSUE TITLE
GADUnifiedNativeAdView, GADMediaView and AdChoices logo disappearing in UICollectionView

### ISSUE THREAD

**Issue by weakfl** [googleads/googleads-mobile-ios-examples#76]
Tested with SDK version 7.32.0 on simulator and real device.

**1. AdChoices logo and GADMediaView disappearing**

**Note:** This happens on cell reuse and **only if the same instance** of `GADUnifiedNativeAd` is used to populate the cell. If a different instance of the same ad is used it's working as expected.

![adchoices_and_gadmediaview_disappearing](https://user-images.githubusercontent.com/614985/45090958-3239a880-b111-11e8-954c-b853c7dbe944.png)

**2. GADUnifiedNativeAdView disappears for videos ads**

Steps to reproduce:
- Press any of the video controls (play, mute, pause, which doesn't matter)
- Scroll the collectionview cell out of the visible area
- Scroll back up -> cell is empty

**Note:** The `UICollectionViewDataSource` doesn't even call `collectionView:cellForItemAtIndexPath:` for this particular item when it comes back into the visible area!!!

**First appearance:**

![gadunifiednativeadview_disappearing_initial](https://user-images.githubusercontent.com/614985/45091570-2f3fb780-b113-11e8-9347-334acd99dadb.png)

<br>

**After pressing a video control and scrolling down and up again:**

![gadunifiednativeadview_disappearing_scroll_back](https://user-images.githubusercontent.com/614985/45091589-42528780-b113-11e8-923e-447b7a9a2522.png)

**Comment by stowy** [comment]
Hi, can you please provide a sample implementation displaying the issue. To me it sounds that they could be related. My thought is that in #1 you say you are using the same native ad instance on multiple cells. Are you certain that you're not displaying the native ad in two cells concurrently? As that is what appears to be the case from your screenshot. This is not a supported use case. A single unified native ad instance can only be displayed in one place at a time. Thus the behavior you are displaying is expected.

I would like to know if you fix #1 by not using the same ad in multiple places, does the 2nd issue still occur?

**Comment by weakfl** [comment]
> My thought is that in issue 1 you say you are using the same native ad instance on multiple cells. Are you certain that you're not displaying the native ad in two cells concurrently? As that is what appears to be the case from your screenshot. This is not a supported use case. A single unified native ad instance can only be displayed in one place at a time. Thus the behavior you are displaying is expected.

Thanks @stowy. I've made sure to use the ads only once and that did indeed resolve issue 1. Out of interest, is this mentioned in the documentation? Did I miss it?

Issue 2 was still a problem though. However, disabling collectionview prefetching did resolve it.
I'm not sure what is causing this, but it might be a similar issue as described here: [rdar://problem/39604024](http://www.openradar.me/39604024)

**Comment by stowy** [comment]
Thanks @weakfl I'll spend a bit more time looking into this to see if there's anything that can be done on our side.

**Comment by stowy** [comment]
@weakfl I was not able to reproduce the issue locally. Since the issue is not related to the Sample Apps in this repo, can I please request that you make a request on the [AdMob developer forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios)? You should provide a sample reproducing the issue and you can chat with them privately to share information such as ad unit ID, etc.

This will enable them to better resolve your issue.

**Comment by TonyKen02** [comment]
I get same this problem! pls show me how to fixed it!!! My version SDK is 10.14.0
