### ISSUE TITLE
7.34.0 version is crashing each time

### ISSUE THREAD

**Issue by shatru-git** [googleads/googleads-mobile-ios-examples#78]
*** -[CFString release]: message sent to deallocated instance 0x115a5f480

**Comment by stowy** [comment]
Hi,

Can you please provide more details as to what conditions you are reproducing this issue? Which sample, what iOS version, what device, what version of Xcode, etc.

**Comment by stowy** [comment]
Not reproducible. Closing. Please report future issues such as this to our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/ios) as these issues are used for issues related more specifically to the samples themselves.
