### ISSUE TITLE
Cannot find an ad network adapter

### ISSUE THREAD

**Issue by gokselkoksal** [googleads/googleads-mobile-ios-examples#79]
Hi! 

I can't get reward ads. Is there a problem with AdMob or the SDK? 

Tried with both 7.34.0 and 7.32.0.

**Error message**:
```
<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
```

**Comment by gokselkoksal** [comment]
It works now! I'd like to know the root cause and what to do in this case though. Is this the right place to log this?

**Comment by stowy** [comment]
Hi, just for clarification, the dummy adapter is supplied when there is a
no fill. So this error occurs when you are not receiving a rewarded ad for
your request, which could be caused by a variety of issues.
