### ISSUE TITLE
Xcode 7.1 Include of non-modular header inside framework module

### ISSUE THREAD

**Issue by Hacoga** [googleads/googleads-mobile-ios-examples#8]
This is a bit strange. After updating to Xcode 7.1. I get these errors 

Include of non-modular header inside framework module 'GoogleMobileAds'

**Comment by Ariequ** [comment]
You should set ENABLE MODULES to Yes.

**Comment by RedBrogdon** [comment]
We've switched up the way we handle the headers for the next version of the SDK, which should correct this issue when it's released.

**Comment by rjgdesign** [comment]
Any update with this? :D
