### ISSUE TITLE
Getting Below issues after run the app

### ISSUE THREAD

**Issue by tikamchandrakar18** [googleads/googleads-mobile-ios-examples#9]
<Google> Cannot find an ad network adapter with the name(s): (
    "com.google.DummyAdapter"
). Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.

**Comment by rjgdesign** [comment]
+1

**Comment by ericleich** [comment]
Just answered this [here](http://stackoverflow.com/questions/31948682/ios-app-from-admob-error-com-google-dummyadapter/34366737#34366737).
